
#pragma once

#define BLANK_CHAR		_T(' ')
#define NULL_CHAR		_T('\0')
#define CR_CHAR			_T('\r')
#define LF_CHAR			_T('\n')
#define APEX_CHAR		_T('\'')
#define DBL_QUOTE_CHAR	_T('\"')
#define ASTERISK_CHAR	_T('*')
#define ZERO_CHAR		_T('0')
#define SHARP_CHAR		_T('#')
#define EXP_CHAR		_T('E')
#define MINUS_CHAR		_T('-')
#define PLUS_CHAR		_T('+')
#define OPEN_ROUND_CHAR _T('(')
#define CLOSE_ROUND_CHAR _T(')')
#define DOT_CHAR		_T('.')
#define TAB_CHAR		_T('\t')
#define URL_SLASH_CHAR	_T('/')
#define SLASH_CHAR		_T('\\')
#define OPEN_CURLY_CHAR		_T('{')
#define CLOSE_CURLY_CHAR	_T('}')
#define PERCENT_CHAR		_T('%')

