//BEGIN_HEADING - file version: 1.0
//WARNING - automatically generated code - DO NOT EDIT THIS FILE!

#include "stdafx.h"

//BEGIN_SOURCE_INCLUDE
#include	"tbdmsfunctions.h"
//END_SOURCE_INCLUDE

#include <atlsafe.h>
#include <TbGeneric\WebServiceStateObjects.h>
#include <TBNameSolver\Templates.h>
//END_HEADING


namespace EasyAttachmentTbDMS {

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) BSTR __GetEasyAttachmentTempPath(HWND _hwnd) throw(...)
	{

		DataStr returnValueParam;
		returnValueParam.SetCollateCultureSensitive(TRUE);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataStr>(_hwnd, &GetEasyAttachmentTempPath);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __OpenBBTraylet(HWND _hwnd) throw(...)
	{

		DataBool returnValueParam;

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool>(_hwnd, &OpenBBTraylet);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __OpenBBSettings(HWND _hwnd) throw(...)
	{

		DataBool returnValueParam;

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool>(_hwnd, &OpenBBSettings);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachFile(HWND _hwnd, BSTR fileName, BSTR description, long documentHandle, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr fileNameParam;
		fileNameParam.SetCollateCultureSensitive(TRUE);
		fileNameParam.SetSoapValue(fileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataLng documentHandleParam;
		documentHandleParam.SetSoapValue(documentHandle);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataLng, DataStr&>(_hwnd, &AttachFile, fileNameParam, descriptionParam, documentHandleParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachArchivedDocument(HWND _hwnd, long archivedDocId, long documentHandle, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataLng archivedDocIdParam;
		archivedDocIdParam.SetSoapValue(archivedDocId);

		DataLng documentHandleParam;
		documentHandleParam.SetSoapValue(documentHandle);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataLng, DataLng, DataStr&>(_hwnd, &AttachArchivedDocument, archivedDocIdParam, documentHandleParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachFolder(HWND _hwnd, BSTR folder, long documentHandle, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr folderParam;
		folderParam.SetCollateCultureSensitive(TRUE);
		folderParam.SetSoapValue(folder);

		DataLng documentHandleParam;
		documentHandleParam.SetSoapValue(documentHandle);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataLng, DataStr&>(_hwnd, &AttachFolder, folderParam, documentHandleParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __ArchiveFile(HWND _hwnd, BSTR fileName, BSTR description, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr fileNameParam;
		fileNameParam.SetCollateCultureSensitive(TRUE);
		fileNameParam.SetSoapValue(fileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr&>(_hwnd, &ArchiveFile, fileNameParam, descriptionParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __ArchiveFolder(HWND _hwnd, BSTR folder, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr folderParam;
		folderParam.SetCollateCultureSensitive(TRUE);
		folderParam.SetSoapValue(folder);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr&>(_hwnd, &ArchiveFolder, folderParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachFileInDocument(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR fileName, BSTR description, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr fileNameParam;
		fileNameParam.SetCollateCultureSensitive(TRUE);
		fileNameParam.SetSoapValue(fileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr, DataStr, DataStr&>(_hwnd, &AttachFileInDocument, documentNamespaceParam, documentKeyParam, fileNameParam, descriptionParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachFolderInDocument(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR folder, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr folderParam;
		folderParam.SetCollateCultureSensitive(TRUE);
		folderParam.SetSoapValue(folder);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr, DataStr&>(_hwnd, &AttachFolderInDocument, documentNamespaceParam, documentKeyParam, folderParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __ArchiveBinaryContent(HWND _hwnd, SAFEARRAY* binaryContent, BSTR sourceFileName, BSTR description, long* archivedDocID, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataBlob binaryContentParam;
		binaryContentParam.SetSoapValue(binaryContent);

		DataStr sourceFileNameParam;
		sourceFileNameParam.SetCollateCultureSensitive(TRUE);
		sourceFileNameParam.SetSoapValue(sourceFileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataLng archivedDocIDParam;
		archivedDocIDParam.SetSoapValue(*archivedDocID);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataBlob, DataStr, DataStr, DataLng&, DataStr&>(_hwnd, &ArchiveBinaryContent, binaryContentParam, sourceFileNameParam, descriptionParam, archivedDocIDParam, resultParam);

		*archivedDocID = archivedDocIDParam.GetSoapValue();
		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachFromTable(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr&>(_hwnd, &AttachFromTable, documentNamespaceParam, documentKeyParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachBinaryContent(HWND _hwnd, SAFEARRAY* binaryContent, BSTR sourceFileName, BSTR description, long documentHandle, long* attachmentId, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataBlob binaryContentParam;
		binaryContentParam.SetSoapValue(binaryContent);

		DataStr sourceFileNameParam;
		sourceFileNameParam.SetCollateCultureSensitive(TRUE);
		sourceFileNameParam.SetSoapValue(sourceFileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataLng documentHandleParam;
		documentHandleParam.SetSoapValue(documentHandle);

		DataLng attachmentIdParam;
		attachmentIdParam.SetSoapValue(*attachmentId);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataBlob, DataStr, DataStr, DataLng, DataLng&, DataStr&>(_hwnd, &AttachBinaryContent, binaryContentParam, sourceFileNameParam, descriptionParam, documentHandleParam, attachmentIdParam, resultParam);

		*attachmentId = attachmentIdParam.GetSoapValue();
		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachBinaryContentInDocument(HWND _hwnd, SAFEARRAY* binaryContent, BSTR sourceFileName, BSTR description, BSTR documentNamespace, BSTR documentKey, long* attachmentId, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataBlob binaryContentParam;
		binaryContentParam.SetSoapValue(binaryContent);

		DataStr sourceFileNameParam;
		sourceFileNameParam.SetCollateCultureSensitive(TRUE);
		sourceFileNameParam.SetSoapValue(sourceFileName);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataLng attachmentIdParam;
		attachmentIdParam.SetSoapValue(*attachmentId);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataBlob, DataStr, DataStr, DataStr, DataStr, DataLng&, DataStr&>(_hwnd, &AttachBinaryContentInDocument, binaryContentParam, sourceFileNameParam, descriptionParam, documentNamespaceParam, documentKeyParam, attachmentIdParam, resultParam);

		*attachmentId = attachmentIdParam.GetSoapValue();
		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __DeleteAttachment(HWND _hwnd, long attachmentID) throw(...)
	{

		DataBool returnValueParam;

		DataLng attachmentIDParam;
		attachmentIDParam.SetSoapValue(attachmentID);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataLng>(_hwnd, &DeleteAttachment, attachmentIDParam);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __DeleteDocumentAttachments(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr&>(_hwnd, &DeleteDocumentAttachments, documentNamespaceParam, documentKeyParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __DeleteAllERPDocumentInfo(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr&>(_hwnd, &DeleteAllERPDocumentInfo, documentNamespaceParam, documentKeyParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) BSTR __GetNewBarcodeValue(HWND _hwnd) throw(...)
	{

		DataStr returnValueParam;
		returnValueParam.SetCollateCultureSensitive(TRUE);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataStr>(_hwnd, &GetNewBarcodeValue);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __GetDefaultBarcodeType(HWND _hwnd, BSTR* type, BSTR* prefix) throw(...)
	{

		DataBool returnValueParam;

		DataStr typeParam;
		typeParam.SetCollateCultureSensitive(TRUE);
		typeParam.SetSoapValue(*type);

		DataStr prefixParam;
		prefixParam.SetCollateCultureSensitive(TRUE);
		prefixParam.SetSoapValue(*prefix);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr&, DataStr&>(_hwnd, &GetDefaultBarcodeType, typeParam, prefixParam);

		SysFreeString(*type);
		*type = typeParam.GetSoapValue();
		SysFreeString(*prefix);
		*prefix = prefixParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachPaperyBarcode(HWND _hwnd, long documentHandle, BSTR barcode) throw(...)
	{

		DataBool returnValueParam;

		DataLng documentHandleParam;
		documentHandleParam.SetSoapValue(documentHandle);

		DataStr barcodeParam;
		barcodeParam.SetCollateCultureSensitive(TRUE);
		barcodeParam.SetSoapValue(barcode);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataLng, DataStr>(_hwnd, &AttachPaperyBarcode, documentHandleParam, barcodeParam);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __AttachPaperyInDocument(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR barcode, BSTR description, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr barcodeParam;
		barcodeParam.SetCollateCultureSensitive(TRUE);
		barcodeParam.SetSoapValue(barcode);

		DataStr descriptionParam;
		descriptionParam.SetCollateCultureSensitive(TRUE);
		descriptionParam.SetSoapValue(description);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataStr, DataStr, DataStr, DataStr&>(_hwnd, &AttachPaperyInDocument, documentNamespaceParam, documentKeyParam, barcodeParam, descriptionParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) long __RunDocumentWithEAPanel(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR* result) throw(...)
	{

		DataLng returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataLng, DataStr, DataStr, DataStr&>(_hwnd, &RunDocumentWithEAPanel, documentNamespaceParam, documentKeyParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) BSTR __GetAttachmentTemporaryFilePath(HWND _hwnd, long attachmentID) throw(...)
	{

		DataStr returnValueParam;
		returnValueParam.SetCollateCultureSensitive(TRUE);

		DataLng attachmentIDParam;
		attachmentIDParam.SetSoapValue(attachmentID);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataStr, DataLng>(_hwnd, &GetAttachmentTemporaryFile, attachmentIDParam);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __MassiveAttachUnattendedMode(HWND _hwnd, BSTR folder, bool splitFile, BSTR* result) throw(...)
	{

		DataBool returnValueParam;

		DataStr folderParam;
		folderParam.SetCollateCultureSensitive(TRUE);
		folderParam.SetSoapValue(folder);

		DataBool splitFileParam;
		splitFileParam.SetSoapValue(splitFile);

		DataStr resultParam;
		resultParam.SetCollateCultureSensitive(TRUE);
		resultParam.SetSoapValue(*result);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataStr, DataBool, DataStr&>(_hwnd, &MassiveAttachUnattendedMode, folderParam, splitFileParam, resultParam);

		SysFreeString(*result);
		*result = resultParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) SAFEARRAY* __SearchAttachmentsForDocument(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR searchText, long location, BSTR searchFields) throw(...)
	{

		DataArray returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr searchTextParam;
		searchTextParam.SetCollateCultureSensitive(TRUE);
		searchTextParam.SetSoapValue(searchText);

		DataLng locationParam;
		locationParam.SetSoapValue(location);

		DataStr searchFieldsParam;
		searchFieldsParam.SetCollateCultureSensitive(TRUE);
		searchFieldsParam.SetSoapValue(searchFields);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataArray, DataStr, DataStr, DataStr, DataLng, DataStr>(_hwnd, &SearchAttachmentsForDocument, documentNamespaceParam, documentKeyParam, searchTextParam, locationParam, searchFieldsParam);


		CComSafeArray<long> sfarreturnValue;
		sfarreturnValue.Create(returnValueParam.GetSize());

		for (long i = 0; i < (long)sfarreturnValue.GetCount(); i++)
		{
			(sfarreturnValue)[i] = ((DataLng*)returnValueParam.GetAt(i))->GetSoapValue();
		}


		return sfarreturnValue.Detach();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) BSTR __SaveAttachmentFileInFolder(HWND _hwnd, long attachmentID, BSTR sharedFolder) throw(...)
	{

		DataStr returnValueParam;
		returnValueParam.SetCollateCultureSensitive(TRUE);

		DataLng attachmentIDParam;
		attachmentIDParam.SetSoapValue(attachmentID);

		DataStr sharedFolderParam;
		sharedFolderParam.SetCollateCultureSensitive(TRUE);
		sharedFolderParam.SetSoapValue(sharedFolder);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataStr, DataLng, DataStr>(_hwnd, &SaveAttachmentFileInFolder, attachmentIDParam, sharedFolderParam);


		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) bool __GetAttachmentBinaryContent(HWND _hwnd, long attachmentID, SAFEARRAY** binaryContent, BSTR* fileName, bool* veryLargeFile) throw(...)
	{

		DataBool returnValueParam;

		DataLng attachmentIDParam;
		attachmentIDParam.SetSoapValue(attachmentID);

		DataBlob binaryContentParam;
		binaryContentParam.SetSoapValue(*binaryContent);

		DataStr fileNameParam;
		fileNameParam.SetCollateCultureSensitive(TRUE);
		fileNameParam.SetSoapValue(*fileName);

		DataBool veryLargeFileParam;
		veryLargeFileParam.SetSoapValue(*veryLargeFile);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataBool, DataLng, DataBlob&, DataStr&, DataBool&>(_hwnd, &GetAttachmentBinaryContent, attachmentIDParam, binaryContentParam, fileNameParam, veryLargeFileParam);

		SafeArrayDestroy(*binaryContent);
		*binaryContent = binaryContentParam.GetSoapValue();
		SysFreeString(*fileName);
		*fileName = fileNameParam.GetSoapValue();
		*veryLargeFile = veryLargeFileParam.GetSoapValue();

		return returnValueParam.GetSoapValue();
	}

	//File: EasyAttachment\TbDMS\TbDMSFunctions.cpp.
	extern "C" __declspec(dllexport) long __GetAttachmentIDByFileName(HWND _hwnd, BSTR documentNamespace, BSTR documentKey, BSTR fileName) throw(...)
	{

		DataLng returnValueParam;

		DataStr documentNamespaceParam;
		documentNamespaceParam.SetCollateCultureSensitive(TRUE);
		documentNamespaceParam.SetSoapValue(documentNamespace);

		DataStr documentKeyParam;
		documentKeyParam.SetCollateCultureSensitive(TRUE);
		documentKeyParam.SetSoapValue(documentKey);

		DataStr fileNameParam;
		fileNameParam.SetCollateCultureSensitive(TRUE);
		fileNameParam.SetSoapValue(fileName);

		returnValueParam = AfxInvokeThreadGlobalFunction<DataLng, DataStr, DataStr, DataStr>(_hwnd, &GetAttachmentIDByFileName, documentNamespaceParam, documentKeyParam, fileNameParam);


		return returnValueParam.GetSoapValue();
	}
}

TB_REGISTER_SOAP_SERVICE(EasyAttachmentTbDMS::CEasyAttachmentTbDMS)