CREATE TABLE "TB_AUTOINCREMENTENTITIES" (
    "ENTITY" /*[SKIPUNICODE]*/ VARCHAR2(128) NOT NULL,
	"LASTNUMBER" NUMBER(10) DEFAULT(0) NULL,
    CONSTRAINT "PK_TB_AUTOINCREMENTENTITIES" PRIMARY KEY
    (
		"ENTITY"
    )
)
GO

CREATE TABLE "TB_AUTONUMBERENTITIES" (
    "ENTITY" /*[SKIPUNICODE]*/ VARCHAR2(128) NOT NULL,
	"FORMATTEDMASK" VARCHAR2(10) DEFAULT ('') NULL,
	"ISYEARENTITY" CHAR(1) DEFAULT('0') NULL,
	"LASTNUMBER" NUMBER(10) DEFAULT(0) NULL,
	"DISABLED" CHAR(1) DEFAULT('0') NULL,
    CONSTRAINT "PK_TB_AUTONUMBERENTITIES" PRIMARY KEY
    (
		"ENTITY"
    ) 
) 
GO

CREATE TABLE "TB_AUTONUMBERENTITIESYEARS" (
	"ENTITY" /*[SKIPUNICODE]*/ VARCHAR2(128) NOT NULL, 
	"YEAR" NUMBER(6) NOT NULL,
	"LASTNUMBER" NUMBER(10) DEFAULT(0) NULL,
    CONSTRAINT "PK_TB_AUTONUMBERENTITIESYEARS" PRIMARY KEY
    (
		"ENTITY",
		"YEAR"
	),
	CONSTRAINT "FK_TB_AUTONUMBERENTITIESYEARS" FOREIGN KEY
    (
        "ENTITY"
    ) REFERENCES "TB_AUTONUMBERENTITIES" 
	(
        "ENTITY"
    )
)
GO