CREATE TABLE "MA_EI_ITCUSTSUPPADDDATA" (
    "CUSTSUPP" VARCHAR2 (12) NOT NULL,
    "CUSTSUPPTYPE" NUMBER (10) DEFAULT(3211264) NOT NULL,
    CONSTRAINT "PK_EI_ITCUSTSUPPADDDATA" PRIMARY KEY
    (
        "CUSTSUPP",
        "CUSTSUPPTYPE"
    )
)
GO

CREATE TABLE "MA_EI_ITCUSTSUPPADDDATADET" (
    "CUSTSUPP" VARCHAR2 (12) NOT NULL,
    "CUSTSUPPTYPE" NUMBER (10) DEFAULT(3211264) NOT NULL,
    "FIELDNAME" VARCHAR2 (256) NOT NULL,
	"FIELDMESSAGE" NUMBER (10) DEFAULT 11599873,
    CONSTRAINT "PK_EI_ITCUSTSUPPADDDATADET" PRIMARY KEY
    (
        "CUSTSUPP",
        "CUSTSUPPTYPE",
        "FIELDNAME"
    )
)
GO
