CREATE TABLE "MA_EI_ITFATELWEBPARAMETERS" ( 
	"PARAMETERID" INTEGER NOT NULL,
    "URL"					VARCHAR2 (256) DEFAULT(''),
    "DBNAME"               VARCHAR2 (32) DEFAULT(''),
    "USERNAME"             VARCHAR2 (128) DEFAULT(''),
    "PASSWORD"             VARCHAR2 (32) DEFAULT(''),
    "COMPANYCODE"          VARCHAR2  (5) DEFAULT(''),
	"USEFATELWEB"			CHAR	 (1) DEFAULT ('0'),
	"XMLVERSION"		   VARCHAR2  (4) DEFAULT (''),
	"ACTIVATIONDATE"	   DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"EXPIRINGDATE"		   DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"PROGRCOMPANYCODE"     VARCHAR2  (5) DEFAULT(''),
	"MAXNUMFILE"           INTEGER DEFAULT(0),
	"MANAGESIGNATURE"      CHAR	 (1) DEFAULT ('0'),
	"PORTALURL" 		   VARCHAR2 (256) DEFAULT(''),
	"SOSMANAGEMENT"      CHAR	 (1) DEFAULT ('1'),
   CONSTRAINT "PK_EI_ITFATELWEBPARAMETERS" PRIMARY KEY
    (
        "PARAMETERID"
    )
)
GO



