CREATE TABLE "MA_EI_ITCOMPANY" (
    "COMPANYID" NUMBER (10) NOT NULL,
    "SENDERISOCOUNTRYCODE" VARCHAR2 (2) DEFAULT (''),
    "SENDERFISCALCODEID" VARCHAR2 (28) DEFAULT (''),
    "LASTSENTNO" VARCHAR2 (5) DEFAULT ('1'),
    "FISCALREGIME" VARCHAR2 (8) DEFAULT (''),
    "PERMANENTBRANCHCODE" VARCHAR2 (8) DEFAULT (''),
    "ISSUERSUBJECT" NUMBER(10) DEFAULT (32047104),
    "FDISOCOUNTRYCODE" VARCHAR2 (2) DEFAULT (''),
    "FDFISCALCODEID" VARCHAR2 (28) DEFAULT (''),
    "FDFISCALCODE" VARCHAR2 (16) DEFAULT (''),
    "FDNATURALPERSON" CHAR (1) DEFAULT ('0'),
    "FDCOMPANYNAME" VARCHAR2 (80) DEFAULT (''),
    "FDNAME" VARCHAR2 (60) DEFAULT (''),
    "FDLASTNAME" VARCHAR2 (60) DEFAULT (''),
    "FDTITLECODE" VARCHAR2 (8) DEFAULT (''),
    "FDEORICODE" VARCHAR2 (17) DEFAULT (''),
    "TIISOCOUNTRYCODE" VARCHAR2 (2) DEFAULT (''),
    "TIFISCALCODEID" VARCHAR2 (28) DEFAULT (''),
    "TIFISCALCODE" VARCHAR2 (16) DEFAULT (''),
    "TINATURALPERSON" CHAR (1) DEFAULT ('0'),
    "TICOMPANYNAME" VARCHAR2 (80) DEFAULT (''),
    "TINAME" VARCHAR2 (60) DEFAULT (''),
    "TILASTNAME" VARCHAR2 (60) DEFAULT (''),
    "TITITLECODE" VARCHAR2 (8) DEFAULT (''),
    "TIEORICODE" VARCHAR2 (17) DEFAULT (''),
	"SENDERTELEPHONE" VARCHAR2 (20) DEFAULT(''),
	"EMAIL" VARCHAR2 (64) DEFAULT (''),

    CONSTRAINT "PK_EI_ITCOMPANY" PRIMARY KEY
    (
        "COMPANYID"
    )
)
GO
