CREATE TABLE "MA_EI_ITDOCADDITIONALDATA" (
    "DOCID" NUMBER (10) NOT NULL,
    "DOCSUBID" NUMBER (10) NOT NULL,
    "LINE" NUMBER (10) NOT NULL,
	"SUBLINE" NUMBER (10) NOT NULL,
    "FIELDNAME" VARCHAR2 (256) NOT NULL,
    "FIELDVALUE" VARCHAR2 (256) DEFAULT (''),
    CONSTRAINT "PK_EI_ITDOCADDITIONALDATA" PRIMARY KEY
    (
        "DOCID",
        "DOCSUBID",
        "LINE",
		"SUBLINE",
        "FIELDNAME"
    )
)
GO
