CREATE TABLE "MA_EI_ITPARAMETERS" ( 
    "PARAMETERID" INTEGER NOT NULL,
    "TAXJOURNAL"				VARCHAR2  (8) DEFAULT(''),
	"TAXJOURNALCREDITNOTE"		VARCHAR2  (8) DEFAULT(''),
    "CONTRACTPROJECTFROMORDERS"  CHAR(1)  DEFAULT('0'),
    "CONTRACTPROJECTFROMJOBS"	CHAR(1)  DEFAULT('0'),
    "SETITEMCODE" 			CHAR (1)  DEFAULT('0'),
    "ITEMCODETYPE" 			VARCHAR2	(35)  DEFAULT(''),
    "LINK"					VARCHAR2	(256)  DEFAULT(''),
	"MANUALREFMANAGEMENT"	CHAR (1)  DEFAULT('0'),
	"ORDERLINENUMBERREFERENCE"	CHAR (1)  DEFAULT('0'),
	"ALWAYSREPORTSALESORDERDATA"	CHAR (1)  DEFAULT('0'),
	"STAMPCHARGESINSUMMARY"	CHAR (1)  DEFAULT('0'),
   CONSTRAINT "PK_EI_ITPARAMETERS" PRIMARY KEY
    (
        "PARAMETERID"
    )
)
GO



