CREATE TABLE "RM_ABSENCEREASONS" ( 
    "REASON" VARCHAR2(8) NOT NULL,
    "DESCRIPTION" VARCHAR2(32) DEFAULT(''),
    "NOTES" VARCHAR2(64) DEFAULT(''),
   CONSTRAINT "PK_RM_ABSENCEREASONS" PRIMARY KEY
    (
        "REASON"
    )
)
GO

