CREATE TABLE "RM_CALENDARS" ( 
    "CALENDAR" VARCHAR2(8) NOT NULL,
    "DESCRIPTION" VARCHAR2(32) DEFAULT(''),
    "EXCLUDEDDAYS" NUMBER(6) DEFAULT(0),
    "EXCLUDEDMONTHS" NUMBER(6) DEFAULT(0),
    "SHIFTDAYS" NUMBER(6) DEFAULT(0),
    "MOVESHIFTSONEXCLDAYS" CHAR(1) DEFAULT('0'),
    "NOTES" VARCHAR2(64) DEFAULT(''),
   CONSTRAINT "PK_RM_CALENDARS" PRIMARY KEY
    (
        "CALENDAR"
    )
)
GO

CREATE TABLE "RM_CALENDARSSHIFTS" ( 
    "CALENDAR" VARCHAR2(8) NOT NULL,
    "LINE" NUMBER(6) NOT NULL,
    "DAYNO" NUMBER(6) DEFAULT(0),
    "STARTINGHOUR" NUMBER(6) DEFAULT(0),
    "STARTINGMINUTE" NUMBER(6) DEFAULT(0),
    "ENDINGHOUR" NUMBER(6) DEFAULT(0),
    "ENDINGMINUTE" NUMBER(6) DEFAULT(0),
    "NOTES" VARCHAR2(64) DEFAULT(''),
   CONSTRAINT "PK_RM_CALENDARSSHIFTS" PRIMARY KEY
    (
        "CALENDAR",
        "LINE"
    ),
   CONSTRAINT "FK_RM_CALENDARSSHIFTS_00" FOREIGN KEY
    (
        "CALENDAR"
    ) REFERENCES "RM_CALENDARS" (
        "CALENDAR"
    )
)
GO

CREATE TABLE "RM_CALENDARSHOLIDAYS" ( 
    "CALENDAR" VARCHAR2(8) NOT NULL,
    "LINE" NUMBER(6) NOT NULL,
    "STARTINGDAY" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
    "ENDINGDAY" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
    "REASONOFEXCLUSION" VARCHAR2(64) DEFAULT(''),
    "NOTES" VARCHAR2(64) DEFAULT(''),
   CONSTRAINT "PK_RM_CALENDARSHOLIDAYS" PRIMARY KEY
    (
        "CALENDAR",
        "LINE"
    ),
   CONSTRAINT "FK_RM_CALENDARSHOLIDAYS_00" FOREIGN KEY
    (
        "CALENDAR"
    ) REFERENCES "RM_CALENDARS" (
        "CALENDAR"
    )
)
GO

