ALTER TABLE "MA_CUSTSUPPBRANCHES"
ADD     "ADMINISTRATIONREFERENCE" VARCHAR2(6) DEFAULT('')
GO

UPDATE "MA_CUSTSUPPBRANCHES" SET "ADMINISTRATIONREFERENCE" = '' WHERE "ADMINISTRATIONREFERENCE" IS NULL
GO
