ALTER TABLE "MA_SALEORDDETAILS"
ADD     "CONTRACTCODE" VARCHAR2(10) DEFAULT('')
GO

UPDATE "MA_SALEORDDETAILS" SET "CONTRACTCODE" = '' WHERE "CONTRACTCODE" IS NULL
GO


UPDATE "MA_SALEORDDETAILS" SET "MA_SALEORDDETAILS"."CONTRACTCODE" = 
(SELECT "MA_SALEORD"."CONTRACTCODE" FROM "MA_SALEORD" WHERE ("MA_SALEORD"."SALEORDID" = "MA_SALEORDDETAILS"."SALEORDID"))
WHERE "MA_SALEORDDETAILS"."INVOICED" = '0' AND "MA_SALEORDDETAILS"."CANCELLED" = '0'
GO


ALTER TABLE "MA_SALEORDDETAILS"
ADD     "PROJECTCODE" VARCHAR2(16) DEFAULT('')
GO

UPDATE "MA_SALEORDDETAILS" SET "PROJECTCODE" = '' WHERE "PROJECTCODE" IS NULL
GO


UPDATE "MA_SALEORDDETAILS" SET "MA_SALEORDDETAILS"."PROJECTCODE" = 
(SELECT "MA_SALEORD"."PROJECTCODE" FROM "MA_SALEORD" WHERE ("MA_SALEORD"."SALEORDID" = "MA_SALEORDDETAILS"."SALEORDID"))
WHERE "MA_SALEORDDETAILS"."INVOICED" = '0' AND "MA_SALEORDDETAILS"."CANCELLED" = '0'
GO