//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NSStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NSStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotificationService.NSStrings", typeof(NSStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while adding Brain Business service url database with the value of:.
        /// </summary>
        internal static string BBServiceUrlError {
            get {
                return ResourceManager.GetString("BBServiceUrlError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brain Business service&apos;s url successfully inserted into the database with the value of: .
        /// </summary>
        internal static string BBServiceUrlSuccesfullyInserted {
            get {
                return ResourceManager.GetString("BBServiceUrlSuccesfullyInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that Brain Business is installed and all the services are started.
        /// </summary>
        internal static string CheckBBServices {
            get {
                return ResourceManager.GetString("CheckBBServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} while retrieving unprocessed forms from BrainBusiness service: .
        /// </summary>
        internal static string ErrorRetrievingForm {
            get {
                return ResourceManager.GetString("ErrorRetrievingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error {0} while sending form to the BrainBusiness service:.
        /// </summary>
        internal static string ErrorSendingForm {
            get {
                return ResourceManager.GetString("ErrorSendingForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during insertion of the generic notification in the database.
        /// </summary>
        internal static string ErrorWhileInsertInDB {
            get {
                return ResourceManager.GetString("ErrorWhileInsertInDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while sending generic notification via XSocket.
        /// </summary>
        internal static string ErrorWhileSendingWithXSocket {
            get {
                return ResourceManager.GetString("ErrorWhileSendingWithXSocket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form {0} for {1}.
        /// </summary>
        internal static string FormNotification {
            get {
                return ResourceManager.GetString("FormNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forms Description list.
        /// </summary>
        internal static string FormsDescriptionList {
            get {
                return ResourceManager.GetString("FormsDescriptionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestone {0} for {1}.
        /// </summary>
        internal static string MilestoneNotification {
            get {
                return ResourceManager.GetString("MilestoneNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milestones list.
        /// </summary>
        internal static string MilestonesList {
            get {
                return ResourceManager.GetString("MilestonesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New notification: workflowID: {0}, username: {1}.
        /// </summary>
        internal static string NewNotifyLog {
            get {
                return ResourceManager.GetString("NewNotifyLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Core successfully started.
        /// </summary>
        internal static string NoficationCoreSuccesfullyStarted {
            get {
                return ResourceManager.GetString("NoficationCoreSuccesfullyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification form for the group in the process identified by workflowInfoID {0}.
        /// </summary>
        internal static string NotificationFormForGroup {
            get {
                return ResourceManager.GetString("NotificationFormForGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
