 CREATE TABLE "DS_ACTIONSLOG" 
   (
    "LOGID" NUMBER(10,0),  
    "PROVIDERNAME" VARCHAR2(20),  
	"DOCNAMESPACE" VARCHAR2(256), 
	"DOCTBGUID" CHAR(38),
	"ACTIONTYPE" NUMBER(10), 		
	"ACTIONDATA" VARCHAR2(1999), 
	"SYNCHDIRECTION" NUMBER(10), 
	"SYNCHXMLDATA" NCLOB, 
	"SYNCHSTATUS" NUMBER(10,0), 
	"SYNCHMESSAGE" VARCHAR2(1024), 
   CONSTRAINT "PK_DS_ACTIONSLOG" PRIMARY KEY
    (
        "LOGID"
    )
)
GO

 CREATE TABLE "DS_SYNCHRONIZATIONINFO" 
   (
    "DOCTBGUID" CHAR(38), 
    "PROVIDERNAME" VARCHAR2(20),  
	"DOCNAMESPACE" VARCHAR2(256), 
	"SYNCHSTATUS" NUMBER(10), 
	"SYNCHDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"SYNCHDIRECTION" NUMBER(10) DEFAULT(31522816), 		
	"LASTACTION" NUMBER(10) DEFAULT(31588352),			
	"WORKERID" NUMBER(10) DEFAULT(0),
	"STARTSYNCHDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"HASDIRTYTBMODIFIED" CHAR(1) DEFAULT('0'),
	 CONSTRAINT "PK_DS_SYNCHRONIZATIONINFO" PRIMARY KEY
    (
        "DOCTBGUID", "PROVIDERNAME"
    )
)
GO 

CREATE TABLE "DS_PROVIDERS" 
   (
	"NAME" VARCHAR2(20),
    "DESCRIPTION" VARCHAR2(256),
	"DISABLED" CHAR(1) DEFAULT ('0'),
	"PROVIDERURL" VARCHAR2(128) DEFAULT(''),
	"PROVIDERUSER" VARCHAR2(50) DEFAULT(''),
	"PROVIDERPASSWORD" VARCHAR2(40) DEFAULT(''),
	"PROVIDERPARAMETERS" VARCHAR2(512) DEFAULT(''),
	"ISEAPROVIDER" CHAR(1) DEFAULT('0'), 
	"IAFMODULES" VARCHAR2(256) DEFAULT(''),
	"TBGUID" CHAR(38) DEFAULT('{00000000-0000-0000-0000-000000000000}'),
	"SKIPCRTVALIDATION" CHAR(1) DEFAULT('0'), 
	 CONSTRAINT "PK_DS_PROVIDERS" PRIMARY KEY
    (
        "NAME"
    )
)
GO 

CREATE TABLE "DS_TRANSCODING"
(	"PROVIDERNAME" VARCHAR2(20),
	"ERPTABLENAME" VARCHAR2(50),
	"ERPKEY" VARCHAR2(256),
    "DOCTBGUID" CHAR(38), 
 	"ENTITYNAME" VARCHAR2(128),
	"ENTITYID" VARCHAR2(256),
	CONSTRAINT "PK_DS_TRANSCODING" PRIMARY KEY
	(
		"PROVIDERNAME",
		"ERPTABLENAME",
		"ERPKEY"
	)	
)
GO

 CREATE TABLE "DS_ACTIONSQUEUE" 
   (
    "LOGID" NUMBER(10,0),  
    "PROVIDERNAME" VARCHAR2(20), 
	"ACTIONNAME" VARCHAR2(256), 
	"SYNCHXMLDATA" NCLOB, 
	"SYNCHSTATUS" NUMBER(10,0), 
	"SYNCHDIRECTION" NUMBER(10), 
	"SYNCHFILTERS" VARCHAR2(1999) DEFAULT(''), 
   CONSTRAINT "PK_DS_ACTIONSQUEUE" PRIMARY KEY
    (
        "LOGID"
    )
)
GO

CREATE TABLE "DS_SYNCHROFILTER"
(	
	"DOCNAMESPACE" VARCHAR2(256), 
	"PROVIDERNAME" VARCHAR2(20),  
	"SYNCHROFILTER" VARCHAR2(1024), 
	CONSTRAINT "PK_DS_SYNCHROFILTER" PRIMARY KEY
	(
		"DOCNAMESPACE",
		"PROVIDERNAME"
	)	
)
GO

CREATE TABLE "DS_ATTACHMENTSYNCHROINFO"
(	
	"PROVIDERNAME" VARCHAR2(20),  	
	"DOCTBGUID" CHAR(38), 
 	"ATTACHMENTID" NUMBER(10) ,
	"DOCNAMESPACE" VARCHAR2(256), 
	"SYNCHSTATUS" NUMBER(10), 
	"SYNCHDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"SYNCHDIRECTION" NUMBER(10) DEFAULT(31522816), 		
	"LASTACTION" NUMBER(10) DEFAULT(31588352),			
	"WORKERID" NUMBER(10) DEFAULT(0),
	CONSTRAINT "PK_DS_ATTACHMENTSYNCHROINFO" PRIMARY KEY
	(
		"PROVIDERNAME",
		"DOCTBGUID",
		"ATTACHMENTID"
	)	
)
GO

CREATE TABLE "DS_VALIDATIONINFO"
(	
	"PROVIDERNAME" VARCHAR2(20),  	
	"DOCTBGUID" CHAR(38),
 	"ACTIONNAME" VARCHAR2(255) DEFAULT (''),
	"DOCNAMESPACE" VARCHAR2(255) DEFAULT (''),	
	"FKERROR" CHAR(1) DEFAULT ('0'),
	"XSDERROR" CHAR(1) DEFAULT ('0'),
	"USEDFORFILTER" CHAR(1) DEFAULT ('0'),
	"MESSAGEERROR" NCLOB DEFAULT (''),	 
	"VALIDATIONDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),	
	CONSTRAINT "PK_DS_VALIDATIONINFO" PRIMARY KEY
	(
		"PROVIDERNAME",
		"DOCTBGUID"
	)	
)
GO

CREATE TABLE "DS_VALIDATIONFKTOFIX"
(	
	"FKTOFIXID" NUMBER(10,0),  
	"PROVIDERNAME" VARCHAR2(20)  DEFAULT (''),  	
	"DOCNAMESPACE" VARCHAR2(255) DEFAULT (''),	
	"TABLENAME" VARCHAR2(255) DEFAULT (''),	
	"FIELDNAME" VARCHAR2(255) DEFAULT (''),	
	"VALUETOFIX" VARCHAR2(255) DEFAULT (''),	
	"RELATEDERRORS" NUMBER(10) DEFAULT(0),
	"VALIDATIONDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),		
	CONSTRAINT "PK_DS_VALIDATIONFKTOFIX" PRIMARY KEY
	(
		"FKTOFIXID"
	)	
)
GO