CREATE TABLE "DS_ATTACHMENTSYNCHROINFO"
(	
	"PROVIDERNAME" VARCHAR2(20),  	
	"DOCTBGUID" CHAR(38), 
 	"ATTACHMENTID" NUMBER(10) ,
	"DOCNAMESPACE" VARCHAR2(256), 
	"SYNCHSTATUS" NUMBER(10), 
	"SYNCHDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),
	"SYNCHDIRECTION" NUMBER(10) DEFAULT(31522816), 		
	"LASTACTION" NUMBER(10) DEFAULT(31588352),			
	"WORKERID" NUMBER(10) DEFAULT(0),
	CONSTRAINT "PK_DS_ATTACHMENTSYNCHROINFO" PRIMARY KEY
	(
		"PROVIDERNAME",
		"DOCTBGUID",
		"ATTACHMENTID"
	)	
)
GO