CREATE TABLE "DS_VALIDATIONINFO"
(	
	"PROVIDERNAME" VARCHAR2(20),  	
	"DOCTBGUID" CHAR(38),
 	"ACTIONNAME" VARCHAR2(255) DEFAULT (''),
	"DOCNAMESPACE" VARCHAR2(255) DEFAULT (''),	
	"FKERROR" CHAR(1) DEFAULT ('0'),
	"XSDERROR" CHAR(1) DEFAULT ('0'),
	"USEDFORFILTER" CHAR(1) DEFAULT ('0'),
	"MESSAGEERROR" NCLOB DEFAULT (''),	 
	"VALIDATIONDATE" DATE DEFAULT (TO_DATE('31-12-1799','DD-MM-YYYY')),		
	CONSTRAINT "PK_DS_VALIDATIONINFO" PRIMARY KEY
	(
		"PROVIDERNAME",
		"DOCTBGUID"
	)	
)
GO