CREATE TABLE "RS_CONFIGURATION"(
	"OFFICEID" NUMBER(10) NOT NULL,
	"USEDENTITIES" VARCHAR2(512) NOT NULL,
	"ISVALID" CHAR(1) NOT NULL,
 CONSTRAINT "PK_RS_CONFIGURATION" PRIMARY KEY
(
	"OFFICEID"
))
GO

CREATE TABLE "RS_SUBJECTS"(
	"SUBJECTID" NUMBER(10) NOT NULL,
	"ISWORKER" CHAR(1) NOT NULL,
	"RESOURCETYPE" VARCHAR2(8) NULL,
	"RESOURCECODE" VARCHAR2(8) NULL,
	"WORKERID" NUMBER(10) NULL,
	"DESCRIPTION" VARCHAR2(128) NOT NULL,
 CONSTRAINT "PK_RS_SUBJECTS" PRIMARY KEY
(
	"SUBJECTID"
)) 
GO

CREATE TABLE "RS_SUBJECTSGRANTS"(
	"SUBJECTID" NUMBER(10) NOT NULL,
	"ENTITYNAME" VARCHAR2(50) NOT NULL,
	"ROWSECURITYID" NUMBER(10) NOT NULL,
	"GRANTTYPE" NUMBER(10) NOT NULL,
	"INHERITED" CHAR(1) NOT NULL,
	"ISIMPLICIT" CHAR(1) NOT NULL,
	"WORKERID" NUMBER(10) NOT NULL,
 CONSTRAINT "PK_RS_SUBJECTSGRANTS" PRIMARY KEY  
(
	"SUBJECTID",
	"ENTITYNAME",
	"ROWSECURITYID"
))
GO

CREATE INDEX "IX_RS_SUBJECTSGRANTS" ON "RS_SUBJECTSGRANTS" ("WORKERID",	"ENTITYNAME", "ROWSECURITYID") 
GO

CREATE TABLE "RS_SUBJECTSHIERARCHY"(
	"MASTERSUBJECTID" NUMBER(10) NOT NULL,
	"SLAVESUBJECTID" NUMBER(10) NOT NULL,
	"NRLEVEL" NUMBER(6) NOT NULL,
 CONSTRAINT "PK_RS_SUBJECTSHIERARCHY" PRIMARY KEY  
(
	"MASTERSUBJECTID",
	"SLAVESUBJECTID",	
	"NRLEVEL"
)) 
GO

CREATE TABLE "RS_TMPOLDHIERARCHIES"(
	"MASTERSUBJECTID" NUMBER(10) NOT NULL,
	"SLAVESUBJECTID" NUMBER(10) NOT NULL,
	"NRLEVEL" NUMBER(6) NOT NULL,
 CONSTRAINT "PK_RS_TMPOLDHIERARCHIES" PRIMARY KEY
(
	"MASTERSUBJECTID",
	"SLAVESUBJECTID",	
	"NRLEVEL"
))
GO
