CREATE TABLE "XE_KEYEXTENSION" (
	"KEYFIELDNAME" /*[SKIPUNICODE]*/ VARCHAR2(32) NOT NULL, 
	"KEYTABLENAME" /*[SKIPUNICODE]*/ VARCHAR2(32) NOT NULL, 
    "KEYEXTENSION" NUMBER(6), 
    "DOCUMENTNAMESPACE" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    CONSTRAINT "PK_XE_KEYEXTENSION" PRIMARY KEY
    (
		"KEYFIELDNAME", 
		"KEYTABLENAME"
	) 
    USING INDEX  )
GO

CREATE TABLE "XE_LOSTANDFOUND" (
	"ORIGINALKEY" VARCHAR2(256) NOT NULL, 
	"KEYTABLENAME" /*[SKIPUNICODE]*/ VARCHAR2(32) NOT NULL, 
    "DOCUMENTNAMESPACE" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    "UNIVERSALKEY" VARCHAR2(256) DEFAULT(''), 
    "CREATIONDATE" DATE, 
    CONSTRAINT "PK_XE_LOSTANDFOUND" PRIMARY KEY
    (
		"ORIGINALKEY", 
		"KEYTABLENAME"
	) 
    USING INDEX  )
GO

CREATE TABLE "XE_PARAMETERS" (
    "IDPARAM" NUMBER(6) NOT NULL,
    "DOMAINNAME" /*[SKIPUNICODE]*/ VARCHAR2(64) DEFAULT(''), 
    "SITENAME" /*[SKIPUNICODE]*/ VARCHAR2(64) DEFAULT(''),
    "SITECODE" /*[SKIPUNICODE]*/ VARCHAR2(4) DEFAULT(''), 
    "ENCODINGTYPE" VARCHAR2(1) DEFAULT('1'), 
    "IMPORTPATH" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    "EXPORTPATH" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    "MAXDOC" NUMBER(6) DEFAULT(10), 
    "MAXKBYTE" NUMBER(6) DEFAULT(100), 
    "USEENVCLASSEXT" CHAR(1) DEFAULT('0'), 
    "ENVPADDINGNUM" NUMBER(6) DEFAULT(4), 
    "USEATTRIBUTE" CHAR(1) DEFAULT('0'), 
    "USEENUMASNUM" CHAR(1) DEFAULT('1'),   
    CONSTRAINT "PK_XE_PARAMETERS" PRIMARY KEY("IDPARAM") 
    USING INDEX  )
GO

INSERT INTO "XE_PARAMETERS"("IDPARAM", "DOMAINNAME", "SITENAME", "SITECODE")
VALUES(1, 'DEFAULT_DOMAIN', 'DEFAULT_SITE', 'DESI')
GO
