
#pragma once

//includere alla fine degli include del .H
#include "beginh.dex"

//=============================================================================
#define MAKE_TOKEN(a)	((void FAR*) MAKELONG(a, 0))
#define GET_TOKEN(a)	((Token)LOWORD(a))

//=============================================================================
enum Token {
T_NULL_TOKEN,
T_SEP =	100, T_ID, T_CMT, T_EOF, 
T_STR, 
T_INT, 		
T_WORD,		
T_LONG,		
T_DWORD,		
T_BOOL,		
T_DOUBLE,	
T_OPERATORS_START,                               
	T_ASSIGN = T_OPERATORS_START,
	T_QUESTION_MARK,                          
	T_PLUS,                                  
	T_MINUS,                                  
	T_STAR,                                   
	T_SLASH,                                  
	T_EXP,                                    
	T_PERC,                                   
	T_LT,                                     
	T_GT,                                     
	T_LE,                                     
	T_GE,                                     
	T_EQ,                                     
	T_NE,                                     
	T_DIFF,                                   
	T_INC,                                   
	T_DEC,                                    
	T_INCASS,                                 
	T_DECASS,                                 
	T_OP_NOT,                                 
	T_OP_AND,                                 
	T_OP_OR,                                  
	T_BW_NOT,                                 
	T_BW_AND,                                 
	T_BW_OR,                                  
	T_BW_XOR,                                 
T_OPERATORS_END  =  T_BW_XOR,
T_BRACKETS_START,
	T_ROUNDOPEN = T_BRACKETS_START,
	T_ROUNDCLOSE,
	T_SQUAREOPEN,                             
	T_SQUARECLOSE,                            
	T_BRACEOPEN,                              
	T_BRACECLOSE,                             
	T_COMMA,                                  
	T_COLON,                                
T_BRACKETS_END = T_COLON,
T_KEYWORDS_START,
	T_FUNCTION_START = T_KEYWORDS_START,  
		T_CCAT = T_FUNCTION_START,
		T_CMAX,                                   
		T_CMIN,                                   
		T_CSUM, 
		T_CCOUNT,
		T_CAVG,
		T_CFIRST,
		T_CLAST,
                      
		T_FABS,                                   
		T_FAPP_DATE,                              
		T_FAPP_YEAR, 

		T_FARRAY_ATTACH,
		T_FARRAY_DETACH,
		T_FARRAY_CLEAR,
		T_FARRAY_COPY,
		T_FARRAY_FIND,
		T_FARRAY_GETAT,
		T_FARRAY_SIZE,
		T_FARRAY_SETAT,
		T_FARRAY_SORT,

        T_FARRAY_ADD,
        T_FARRAY_APPEND,
        T_FARRAY_INSERT,
        T_FARRAY_REMOVE,
        T_FARRAY_CONTAINS,
        T_FARRAY_CREATE,
		T_FARRAY_SUM,		

		T_FASC,                                   
		T_FCDOW,                                  
		T_FCEIL,                                  
		T_FCHR,                                   
		T_FCMONTH,                               
		T_FCONVERT,                                  
		T_FCTOD,                                  
		T_FDATE,                                  
		T_FDATETIME,                              
		T_FDAY,                                   
		T_FDTOC,                                  
		T_FELAPSED_TIME,                          
		T_FFIND,  
		T_FREMOVENEWLINE,
		T_FREPLACE,                                  
		T_FREVERSEFIND,                                  
		T_FFLOOR,                                 
		T_FFORMAT,                                
		T_FINT,                                   
		T_FLAST_MONTH_DAY,                        
		T_FLEFT,                                  
		T_FLEN,                                   
		T_FLONG,                                  
		T_FLOWER,                                 
		T_FLTRIM,                                 
		T_FMAX,                                   
		T_FMIN,                                   
		T_FMOD,                                   
		T_FMONTH,                                 
		T_FMONTH_DAYS,                            
		T_FMONTH_NAME,                            
		T_FRIGHT,                                 
		T_FROUND,                                 
		T_FRTRIM,                                 
		T_FSIGN,                                  
		T_FSPACE,                                 
		T_FSTR,                                   
		T_FSUBSTR,                                
		T_FSUBSTRWW,                              
		T_FTIME,                                  
		T_FTRIM,                                  
		T_FTYPED_BARCODE,                         
		T_FGETBARCODE_ID,                         
		T_FUPPER,                                 
		T_FVAL,                                   
		T_FYEAR,                                  
		T_FDAYOFWEEK,							 
		T_FWEEKOFMONTH,							 
		T_FWEEKOFYEAR,							 
		T_FGIULIANDATE,							 
		T_FDAYOFYEAR,							 
		T_FLOADTEXT,								 
		T_FSAVETEXT,								 
		T_FLOCALIZE,	
		T_FRGB,

		T_FGETAPPTITLE_FROM_NS,							 
		T_FGETMODTITLE_FROM_NS,							 
		T_FGETDOCTITLE_FROM_NS,	
		T_FGETPATH_FROM_NS,	
		T_FGETNS_FROM_PATH,	

		T_FGETDATABASETYPE,
		T_FISDATABASEUNICODE,							 
		T_FGETEDITION,
		T_FGETPRODUCTLANGUAGE,
		T_FGETCOMPUTERNAME,							 
		T_FGETLOGINNAME,							 
		T_FGETWINDOWUSER,							 
		T_FGETINSTALLATIONNAME,							 
		T_FGETINSTALLATIONPATH,							 
		T_FGETINSTALLATIONVERSION,							 
		T_FGETCOMPANYNAME,	
		T_FGETCULTURE,
		T_FGETUSERDESCRIPTION,

		T_FGETNEWGUID,							 

		T_FMAKELOWERLIMIT,			
		T_FMAKEUPPERLIMIT,			
		T_FGETUPPERLIMIT,	

		T_FCONTENTOF,
		T_FVALUEOF,

		T_FTABLEEXISTS,			
		T_FFILEEXISTS,

		T_FGETSETTING,			
		T_FSETSETTING,			

		T_FSETCULTURE,

		T_FISREMOTEINTERFACE,							 
		T_FISRUNNINGFROMEXTERNALCONTROLLER,

		T_FDECODE,	
		T_FCHOOSE,
		T_FIIF,

		T_FISADMIN,

		T_FISEMPTY,
		T_FISNULL,

		T_FDATEADD,		
		T_FWEEKSTARTDATE,		
		T_FISLEAPYEAR,		
		T_FEASTERSUNDAY,	

		T_FWILDCARD_MATCH,

		T_FREPLICATE,
		T_FPADLEFT,
		T_FPADRIGHT,
		T_FCOMPARE_NO_CASE,

		T_FSEND_BALLOON,
		T_FFORMAT_TBLINK,

		T_FISWEB,
		T_FISACTIVATED,			

		T_FUNCTION_PUBLIC_END = T_FISACTIVATED,
		
		//undocumented	
		T_FEXECUTESCRIPT,
		T_FGETTITLE,
		T_FPREV_VALUE,
		T_FNEXT_VALUE,

		T_FGETTHREADCONTEXT,							 
		T_FOWNTHREADCONTEXT,	
	
		//undocumented, unsupported	
		T_FCOLUMN_GETAT,
		T_FCOLUMN_FIND,
		T_FCOLUMN_SIZE,
		T_FCOLUMN_SUM,

		T_FRECORD_GETFIELD,
		T_FOBJECT_GETFIELD,

		T_FTYPEOF,		
		T_FADDRESSOF,	

		T_FUNCTION_END = T_FADDRESSOF,
	T_ABORT,
	T_AFTER,                                  
	T_ALIAS,                                 
	T_ALIASES,                                
	T_ALIGN,                                  
	T_ALL,                                    
	T_ALWAYS, 
	T_ANCHOR_PAGE_LEFT,    //printer attributes for single field
	T_ANCHOR_PAGE_RIGHT, 
	T_ANCHOR_COLUMN_ID,		//end printer attributes for single field
	T_AND,                                    
	T_APPEND,                                 
	T_ARCHIVE,                                
	T_ARRAY,                                  
	T_ASK,                                  
	//T_BARCODE,                                
	T_BARCODE_STRIP,                                
	T_BEFORE,                                 
	T_BEGIN,                                  
	T_BETWEEN,                                
	T_BKGCOLOR,                               
	T_BLANK,                                  
	T_BODY,                                   
	T_BOLD,                                   
	T_BORDERS,                                
	T_BOTTOM,                                 
	T_BREAK,                                  
	T_BREAKING,                               
	T_BY,                                     
	T_CALL,                                   
	T_CALL_DLL,                               
	T_CASE,                                   
	T_CELL,                                   
	T_CHECK, 
	T_CHART, 
	T_CLOSE,                                  
	T_CMD,                                    
	T_COLTOTAL,                              
	T_COLUMN,
	T_COLUMN_ANCHOR_LEFT,         //printer columns tokens
	T_COLUMN_ANCHOR_RIGHT,
	T_COLUMN_FIXED,
	T_COLUMN_HIDE_WHEN_EMPTY,
	T_COLUMN_OPTIMIZE_WIDTH,      
	T_COLUMN_SPLITTER,			//end printer columns tokens
	T_COLUMNS,                                
	T_COLUMN_PEN,                             
	T_COLUMN_TITLES,                          
	T_COMMENT_SEP,                            
	T_CONST,                                  
	T_CONTAINS,                               
	T_CONTINUE,                               
	T_COPYRIGHT,                              
	T_CREATE,                                 
	T_CREATE_XSD,                                 
	T_DATASOURCE,
	T_DDE,                                    
	T_DEBUG,                                
	T_DEFAULT,                                
	T_DEFINE,                                 
	T_DELETE,                                 
	T_DESCENDING,                             
	T_DIALOG,                                 
	T_DISPLAY,                                
	T_DISPLAY_FREE_FIELDS,
	T_DISPLAY_TABLE_ROW,                      
	T_DISTINCT,                               
	T_DROPSHADOW,                                    
	T_DO,                                     
	T_ELSE,                                   
	T_END,                                    
	T_ESCAPE,                                 
	T_EVAL,                                   
	T_EVENTS,                                 
	T_EXEC, 
	T_EXPORT,                                 
	T_EXTENSION,                              
	T_FACENAME,                               
	T_FALSE,                                  
	T_FIELD,                                  
	T_FILE,                                   
	T_FISCAL_END,                             
	T_FLOAT,                                  
	T_FONTSTYLE,                              
	T_FONTSTYLES,                             
	T_FOR, 
	T_FORCE,
	T_FORMATSTYLE,                            
	T_FORMATSTYLES,                           
	T_FORMFEED,                               
	T_FROM,                                   
	T_FUNCPROTO,                             
	T_GOTO,                                   
	T_BITMAP,                                  
	T_GROUP,                                  
	T_HAVING,                                 
	T_HEIGHTS,                                
	T_HELP,                                   
	T_HIDDEN,                                 
	T_HIDE_ALL_TABLE_TITLE,                   
	T_HIDE_LS0,                               
	T_HIDE_MS0,                               
	T_HIDE_TABLE_TITLE,                       
	T_HOTLINK,                                
	T_IF,
	T_INCH,                                   
	T_INDEX,                                  
	T_INIT,                                   
	T_INPUT,                                  
	T_INSERT,                                 
	T_INTERLINE,                              
	T_INTO,                                   
	T_INVALID,
	T_INVERT_ORIENTATION,
	T_IS,                                     
	T_ITALIC,                                 
	T_KEY,                                    
	T_LABEL,                                  
	T_LANDSCAPE,                              
	T_EASYVIEW,                     
	T_LIKE,                                   
	T_LOGIC,                                  
	T_LOWER_LIMIT,                            
	T_MARGINS,                                
	T_MAXIMIZED,                              
	T_MENU,                                   
	T_MENUITEM,                               
	T_MESSAGE_BOX,                            
	T_MINIMIZED,                              
	T_NATIVE,                                 
	T_NEWLINE,                                
	T_NEXTLINE,                               
	T_NODUPKEY,                               
	T_NOT,                                    
	T_NOTOKEN,                                
	T_NO_BOB,                                 
	T_NO_BOL,                                 
	T_NO_BOR,                                 
	T_NO_BORDERS,                             
	T_NO_BOT,                                 
	T_NO_CON_BKGN_BITMAP,                     
	T_NO_CON_BORDERS,                         
	T_NO_CON_LABELS,                          
	T_NO_CON_TITLES,                          
	T_NO_CSE,                                 
	T_NO_CTL,                                 
	T_NO_CTR,                                 
	T_NO_CTS,                                 
	T_NO_CTT,                                 
	T_NO_HRULER,                             
	T_NO_INTERFACE,							 
	T_NO_PRN_BKGN_BITMAP,                     
	T_NO_PRN_BORDERS,                         
	T_NO_PRN_LABELS,                          
	T_NO_PRN_TITLES,                          
	T_NO_STATUSBAR,                           
	T_NO_TOB,                                 
	T_NO_TOL,                                 
	T_NO_TOOLBAR,                             
	T_NO_TOR,                                 
	T_NO_TTL,                                 
	T_NO_TTR,                                 
	T_NO_TTT,                                 
	T_NO_VRULER,                              
	T_NULL,                                   
	T_NUMERIC,   
	//T_TOBJECT,
	T_OF,                                     
	T_ON,                                     
	T_ONLY_GRAPH,                             
	T_OPEN,                                   
	T_OPTIONS,                                
	T_OR,                                     
	T_ORDER,                                  
	T_ORIGIN,
	//T_OWNER_ID,
	T_PADDED,                                 
	T_PAGE_INFO,
	T_PAGE_LAYOUT,
	T_PAGE_PRINTER_INFO,
	T_PAGE_HSPLITTER,
	T_PAGE_VSPLITTER,
	T_PATH,                                   
	T_PEN,                                    
	T_POPUP,                                  
	T_POSTFIX,                                
	T_PRECISION,                              
	T_PREFIX,                                 
	T_PROCEDURE,                              
	T_PROCEDURES,                              
	T_PROMPT,                                 
	T_QUERIES,                                  
	T_QUERY,
	T_QUIT,
	T_RATIO,                                  
	T_READ_ONLY,                              
	T_RECT,                                   
	T_RELEASE,                                
	T_REPORT,
	T_REPORTPRODUCER,
	T_REPORTS,                                
	T_RESET,
	T_RETURN,
	T_COLOR,                                 
	T_RNDRECT,                                
	T_ROW,                                    
	T_RULES,                                 
	T_SAVE,                                   
	T_SEGMENTED,                              
	T_SELECT,                                 
	T_SEPARATOR,                              
	T_SIZE,                                   
	T_SIZEOF,                                 
	T_SPACELINE,                              
	T_SPAWN,                                  
	T_SPECIAL_FIELD,                          
	T_SQL_EXEC,                               
	T_SQRRECT,                                
	T_STRIKEOUT,                              
	T_STRUCT,                                 
	T_STYLE,                                  
	T_SUBTOTAL,                               
	T_SUBTOTALS,                              
	T_SWITCH,                                 
	T_TAB,                                    
	T_TABLE,                                  
	T_TABLES,                                 
	T_TBOOL,                                  
	T_TDOUBLE,                                
	T_TENUM,                                  
	T_TEXT,                                   
	T_TEXTCOLOR,                              
	T_THEN,                                   
	T_THOUSAND,                               
	T_TINTEGER,                               
	T_TITLE,                                  
	T_TLONG,                                  
	T_TMONEY,                                 
	T_TOP,                                    
	T_TOTAL,                                  
	T_TOTALS,                                 
	T_TPERCENT,                               
	T_TQUANTITY,                              
	T_TRANSPARENT,                            
	T_TRUE,                                   
	T_TSET,                                   
	T_TSTR,                                   
	T_TVAR,                                   
	T_TYPE,                                   
	T_TYPEDEF,                                
	T_UNDEF,                                  
	T_UNDERLINE,                                                               
	T_UPDATE,                                 
	T_UPPER_LIMIT,                            
	T_USE_DRAFT_FONT,                         
	T_VAR,                                    
	T_WEEKDAY,                                
	T_WHEN,                                   
	T_WHERE,                                  
	T_WHILE,                                  
	T_WIDTH,                                  
	T_ROWSEP,                                 
	T_METAFILE,                               
	T_PROPORTIONAL,                           
	T_INCLUDE,								 
	T_BUILD_IDS,								 
	T_STRINGTABLE,							 
	T_OBJECTS,								 
	T_STATUS,								 
	T_UUID,									 
	T_CONDITIONAL,							 
	T_AUTOINCREMENTAL,						 
	T_PROPERTIES,							 
	T_SUBJECT,								 
	T_AUTHOR,								 
	T_COMMENTS,								 
	T_ORDER_FIND_FIELD,	
	T_FIND_SLAVE_FIELD,
	T_HTMLFILE,								 
	T_CONTROLS,								 
	T_CMDSHORTCUT,                            
	T_OPTIONAL,								 
	T_REINIT,								 
	T_TBLOB,									 
	T_TTEXT,									 
	T_LINKS,								 
	T_LINKFORM,								 
	T_LINKFUNCTION,								 
	T_LINKRADAR,								 
	T_LINKREPORT,
	T_LINKURL,
	T_MAIL,									 
	T_STATIC,								 
	T_DIALOGS,								 
	T_DEVELOPMENT,							 
	T_RADARS,								 
	T_CFG,	
	T_FINALIZE,
	T_NO_WEB,
	T_DYNAMIC,
	T_EXPAND,		
	T_IN,	
	T_OUT,		
	T_REF,		
	T_COL,
	T_TOOLTIP,								 
	T_TEMPLATE,
	T_FULL,
	T_AS,
	T_NO_XML,
	T_VMERGE_EMPTY_CELL,
	T_VMERGE_EQUAL_CELL,
	T_VMERGE_TAIL_CELL,
	T_TITLE_BOTTOM,
	T_COLTITLE_BOTTOM,
	T_TOTAL_TOP,
	T_DEFAULTSECURITYROLES,
	T_REPEATER,   
	T_CONTEXT,
	T_MULTI_SELECTIONS,
	T_RECORD,                                  
	T_INNER,
	T_OUTER,
	T_JOIN,
	T_CROSS,
	T_HTML,
	T_LAYER,

	T_TITLELINE,
	T_SUBTITLELINE,

	T_DISPLAY_CHART,
	T_CHART_CATEGORIES,
	T_CHART_SERIES,
	T_CHART_LEGEND,
	T_CHART_AXIS,

T_AVAIL_START,                            
	T_AVAIL_1 = T_AVAIL_START,
	T_AVAIL_2,                                
	T_AVAIL_3,                                
	T_AVAIL_4,                                
T_KEYWORDS_END= T_AVAIL_4,
T_STARTTOKEN
};

// list of tokens with same word but different means
//
#define T_TDATE            T_FDATE			// Date data type
#define T_TDATETIME        T_FDATETIME		// DateTime data type
#define T_TTIME            T_FTIME			// Time data type
#define T_TELAPSED_TIME    T_FELAPSED_TIME	// ElapsedTime data type

#define T_ASCENDING        T_FASC			// Ascending key for Order By predicate

#define T_UPPER            T_FUPPER
#define T_LOWER            T_FLOWER

#define T_LEFT             T_FLEFT
#define T_RIGHT            T_FRIGHT

//=============================================================================
//Tipo della riga della TokenTable
typedef struct SToken 
{
	Token m_TokenId;
	CString	m_sToken;

	static Token GetToken(const struct SToken* tt, CString st)
	{
		for(int i=0; tt[i].m_TokenId != T_NULL_TOKEN; i++)
		{
			if( tt[i].m_sToken.CompareNoCase(st) == 0)
				return tt[i].m_TokenId;
		}
		return T_NOTOKEN; 
	}

	static CString ToString(const struct SToken* tt, int t)
	{
		for(int i=0; tt[i].m_TokenId != T_NULL_TOKEN; i++)
		{
			if (tt[i].m_TokenId == t)
				return tt[i].m_sToken;
		}
		ASSERT(FALSE);
		return _T(""); 
	}
} TToken;

//=============================================================================

class TB_EXPORT TokensTable
{   
protected:
	CMapStringToPtr*	m_pOperators;
	CMapStringToPtr*	m_pBrackets;
	CMapStringToPtr*	m_pKeywords;

	const TToken * m_Tokens;
	int m_nSize;

public:
	TokensTable(const TToken * arTokens, int size);
	virtual ~TokensTable();
	
public:
	void	LoadStandardTokens	();

	Token	GetOperatorsToken	(LPCTSTR pszLexeme) const;
	Token	GetBracketsToken	(LPCTSTR pszLexeme) const;
	Token	GetKeywordsToken	(LPCTSTR pszLexeme) const;
	Token	GetTokenFromMap		(CMapStringToPtr* pMap, LPCTSTR pszLexeme) const;

	BOOL	IsInLanguage		(const CString& sToken) const;
	CString ToString			(Token t) const;
};

//=============================================================================        
TB_EXPORT const TokensTable*	AFXAPI AfxGetTokensTable();

#include "endh.dex"
