CREATE TABLE "TB_DBMARK" (
	"APPLICATION" /*[SKIPUNICODE]*/ VARCHAR2(20) NOT NULL, 
	"ADDONMODULE" /*[SKIPUNICODE]*/ VARCHAR2(40) NOT NULL, 
    "DBRELEASE" NUMBER(6) DEFAULT (-1) NOT NULL, 
    "RELEASEDATE" DATE DEFAULT(sysdate), 
    "STATUS" CHAR(1) DEFAULT('1') NOT NULL , 
    "EXECLEVEL3" CHAR(1) DEFAULT('0')  NOT NULL, 
    "UPGRADELEVEL" NUMBER(6) DEFAULT(0)  NOT NULL, 
    "STEP" NUMBER(6) DEFAULT(0)  NOT NULL, 
    CONSTRAINT "PK_TB_DBMARK" PRIMARY KEY
    (
		"APPLICATION", 
		"ADDONMODULE"
	) 
    USING INDEX  
    )
GO