//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.TaskBuilderNet.TbHermesBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMS_Attachment
    {
        public int AttachmentID { get; set; }
        public int ErpDocumentID { get; set; }
        public int CollectionID { get; set; }
        public int ArchivedDocID { get; set; }
        public Nullable<int> TBCreatedID { get; set; }
        public Nullable<int> TBModifiedID { get; set; }
        public Nullable<System.DateTime> TBCreated { get; set; }
        public Nullable<System.DateTime> TBModified { get; set; }
        public Nullable<bool> IsMainDoc { get; set; }
        public string Description { get; set; }
        public string AbsoluteCode { get; set; }
        public string LotID { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual DMS_ArchivedDocument DMS_ArchivedDocument { get; set; }
    }
}
