//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.TaskBuilderNet.TbHermesBL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OM_GoogleEvents
    {
        public int GoogleEventId { get; set; }
        public string Id { get; set; }
        public int WorkerId { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public System.DateTime EventStart { get; set; }
        public System.DateTime EventEnd { get; set; }
        public string Status { get; set; }
        public System.DateTime Updated { get; set; }
        public string Visibility { get; set; }
        public string RecurringEventId { get; set; }
        public string Recurrence { get; set; }
        public string HtmlLink { get; set; }
        public string Creator { get; set; }
        public string IsDeleted { get; set; }
        public System.DateTime TBCreated { get; set; }
        public System.DateTime TBModified { get; set; }
        public int TBCreatedID { get; set; }
        public int TBModifiedID { get; set; }
        public string TimeZone { get; set; }
        public System.DateTime OriginalStartTime { get; set; }
        public string IsException { get; set; }
    }
}
