//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.Console.Plugin.ServicesAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microarea.Console.Plugin.ServicesAdmin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can execute some actions that allows you to interact with the {0} web service. .
        /// </summary>
        internal static string ActionsDescri {
            get {
                return ResourceManager.GetString("ActionsDescri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string ActiveWebService {
            get {
                return ResourceManager.GetString("ActiveWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string AddressHeader {
            get {
                return ResourceManager.GetString("AddressHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string aDefault {
            get {
                return ResourceManager.GetString("aDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service has been restarted!.
        /// </summary>
        internal static string AfterRestartService {
            get {
                return ResourceManager.GetString("AfterRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (All).
        /// </summary>
        internal static string AllElements {
            get {
                return ResourceManager.GetString("AllElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show private sessions.
        /// </summary>
        internal static string AllSession {
            get {
                return ResourceManager.GetString("AllSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string ApplicationHeader {
            get {
                return ResourceManager.GetString("ApplicationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applications.
        /// </summary>
        internal static string Applications {
            get {
                return ResourceManager.GetString("Applications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Server.
        /// </summary>
        internal static string ApplicationServerlbl {
            get {
                return ResourceManager.GetString("ApplicationServerlbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Server Monitory.
        /// </summary>
        internal static string ApplicationToolTipString {
            get {
                return ResourceManager.GetString("ApplicationToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign licenses to users.
        /// </summary>
        internal static string ArticlesLicensesToolTip {
            get {
                return ResourceManager.GetString("ArticlesLicensesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licences to users.
        /// </summary>
        internal static string ArticleUsers {
            get {
                return ResourceManager.GetString("ArticleUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm deleting?.
        /// </summary>
        internal static string AskIfContinueDelete {
            get {
                return ResourceManager.GetString("AskIfContinueDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm disconnection for user {0}?.
        /// </summary>
        internal static string AskIfContinueLogOff {
            get {
                return ResourceManager.GetString("AskIfContinueLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want remove locks for company {0}?.
        /// </summary>
        internal static string AskIfDeleteCompanyLocks {
            get {
                return ResourceManager.GetString("AskIfDeleteCompanyLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want remove locks for company {0} on table {1}?.
        /// </summary>
        internal static string AskIfDeleteCompanyTableLocks {
            get {
                return ResourceManager.GetString("AskIfDeleteCompanyTableLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want remove locks for company {0} and user {1}?.
        /// </summary>
        internal static string AskIfDeleteCompanyUserLocks {
            get {
                return ResourceManager.GetString("AskIfDeleteCompanyUserLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want delete the locks of user {0} of company {1}?.
        /// </summary>
        internal static string AskIfDeleteUserCompanyLocks {
            get {
                return ResourceManager.GetString("AskIfDeleteUserCompanyLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want remove locks for user {0}?.
        /// </summary>
        internal static string AskIfDeleteUserLocks {
            get {
                return ResourceManager.GetString("AskIfDeleteUserLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to restart the {0} service?.
        /// </summary>
        internal static string AskIfRestartService {
            get {
                return ResourceManager.GetString("AskIfRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you confirm the save of traced data?.
        /// </summary>
        internal static string AskIfSaveTraceXmlFormat {
            get {
                return ResourceManager.GetString("AskIfSaveTraceXmlFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality requires a valid authentication, so this operation will not be executed..
        /// </summary>
        internal static string AuthenticationTokenNotValid {
            get {
                return ResourceManager.GetString("AuthenticationTokenNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to contact the web service {0} on the server {1}.
        /// </summary>
        internal static string CannotContactWebService {
            get {
                return ResourceManager.GetString("CannotContactWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reload the binds between users and articles..
        /// </summary>
        internal static string CannotReloadUserArticleBindings {
            get {
                return ResourceManager.GetString("CannotReloadUserArticleBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to restart the {0} service!.
        /// </summary>
        internal static string CannotRestartWebService {
            get {
                return ResourceManager.GetString("CannotRestartWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to stop service {0}!.
        /// </summary>
        internal static string CannotStopWebService {
            get {
                return ResourceManager.GetString("CannotStopWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm restarting process of the web service.
        /// </summary>
        internal static string CaptionRestartService {
            get {
                return ResourceManager.GetString("CaptionRestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to delete all associations?.
        /// </summary>
        internal static string ClearAllAssociation {
            get {
                return ResourceManager.GetString("ClearAllAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyContainers {
            get {
                return ResourceManager.GetString("CompanyContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string CompanyHeader {
            get {
                return ResourceManager.GetString("CompanyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string ComputerName {
            get {
                return ResourceManager.GetString("ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password is wrong.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create locks file log.
        /// </summary>
        internal static string CreateLocksLogFile {
            get {
                return ResourceManager.GetString("CreateLocksLogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy installation path.
        /// </summary>
        internal static string CutWebServiceUrl {
            get {
                return ResourceManager.GetString("CutWebServiceUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBaseObjects.
        /// </summary>
        internal static string DataBaseObjects {
            get {
                return ResourceManager.GetString("DataBaseObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string DataHeader {
            get {
                return ResourceManager.GetString("DataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date/time.
        /// </summary>
        internal static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defined in.
        /// </summary>
        internal static string DefinedInto {
            get {
                return ResourceManager.GetString("DefinedInto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Locks.
        /// </summary>
        internal static string DeleteLocks {
            get {
                return ResourceManager.GetString("DeleteLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some features of the product it is necessary to check the license and therefore they must be associated to an Application User..
        /// </summary>
        internal static string Descr1 {
            get {
                return ResourceManager.GetString("Descr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These associations are created automatically with first use by User..
        /// </summary>
        internal static string Descr2 {
            get {
                return ResourceManager.GetString("Descr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The form allows modifying these relations for disabling a feature to a user and associate it to another one..
        /// </summary>
        internal static string Descr3 {
            get {
                return ResourceManager.GetString("Descr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load events log for {0}..
        /// </summary>
        internal static string EventLogUnavailable {
            get {
                return ResourceManager.GetString("EventLogUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention! There are connected users, do you want to continue? Answering &apos;Yes&apos; the users must necessarily connect again, after the restart of service.
        /// </summary>
        internal static string ExistLoggedUsers {
            get {
                return ResourceManager.GetString("ExistLoggedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter description already exist in list.
        /// </summary>
        internal static string ExistParameterDescription {
            get {
                return ResourceManager.GetString("ExistParameterDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter name already exist.
        /// </summary>
        internal static string ExistParameterName {
            get {
                return ResourceManager.GetString("ExistParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Licence Management.
        /// </summary>
        internal static string Floating {
            get {
                return ResourceManager.GetString("Floating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot date is wrong! (start date is greater than finish date).
        /// </summary>
        internal static string FromDateWrong {
            get {
                return ResourceManager.GetString("FromDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function.
        /// </summary>
        internal static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∞.
        /// </summary>
        internal static string Infinite {
            get {
                return ResourceManager.GetString("Infinite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the description of new parameter.
        /// </summary>
        internal static string InsertNewDescription {
            get {
                return ResourceManager.GetString("InsertNewDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert name of new parameter.
        /// </summary>
        internal static string InsertNewName {
            get {
                return ResourceManager.GetString("InsertNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert the value of new parameter.
        /// </summary>
        internal static string InsertNewValue {
            get {
                return ResourceManager.GetString("InsertNewValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data.
        /// </summary>
        internal static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string KeyHeader {
            get {
                return ResourceManager.GetString("KeyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to kill the selected process?.
        /// </summary>
        internal static string KillTb {
            get {
                return ResourceManager.GetString("KillTb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} {1} does not respond. Do you want to terminate it now?.
        /// </summary>
        internal static string KillUnresponsive {
            get {
                return ResourceManager.GetString("KillUnresponsive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection time.
        /// </summary>
        internal static string LifeTime {
            get {
                return ResourceManager.GetString("LifeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row Number.
        /// </summary>
        internal static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locks.
        /// </summary>
        internal static string LocksGroup {
            get {
                return ResourceManager.GetString("LocksGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users connected to the application.
        /// </summary>
        internal static string LoginedUsersToolTip {
            get {
                return ResourceManager.GetString("LoginedUsersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User disconnection.
        /// </summary>
        internal static string LogOffTitle {
            get {
                return ResourceManager.GetString("LogOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Viewer.
        /// </summary>
        internal static string LogViewer {
            get {
                return ResourceManager.GetString("LogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration Console.
        /// </summary>
        internal static string MicroareaConsole {
            get {
                return ResourceManager.GetString("MicroareaConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Waiting for user input).
        /// </summary>
        internal static string Modal {
            get {
                return ResourceManager.GetString("Modal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Named Licence Management.
        /// </summary>
        internal static string Named {
            get {
                return ResourceManager.GetString("Named", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before select an item.
        /// </summary>
        internal static string NoArticolSel {
            get {
                return ResourceManager.GetString("NoArticolSel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: license file not found.
        /// </summary>
        internal static string NoCallFile {
            get {
                return ResourceManager.GetString("NoCallFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No locks are present.
        /// </summary>
        internal static string NoLocksFounded {
            get {
                return ResourceManager.GetString("NoLocksFounded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages available in Event Viewer..
        /// </summary>
        internal static string NoMsgAvailable {
            get {
                return ResourceManager.GetString("NoMsgAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Running.
        /// </summary>
        internal static string NonActiveWebService {
            get {
                return ResourceManager.GetString("NonActiveWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No active processes.
        /// </summary>
        internal static string NoProcesses {
            get {
                return ResourceManager.GetString("NoProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! No data exist with the current search parameters! Save operation is stopped!.
        /// </summary>
        internal static string NoTracedRecords {
            get {
                return ResourceManager.GetString("NoTracedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service {0} is not running.
        /// </summary>
        internal static string NotRestartWebService {
            get {
                return ResourceManager.GetString("NotRestartWebService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display the events from {0} traced in the Event Log. Only the first {1} rows will be shown..
        /// </summary>
        internal static string OperationsTrace {
            get {
                return ResourceManager.GetString("OperationsTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap People53 {
            get {
                object obj = ResourceManager.GetObject("People53", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to process.
        /// </summary>
        internal static string Process {
            get {
                return ResourceManager.GetString("Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide private sessions.
        /// </summary>
        internal static string PublicSection {
            get {
                return ResourceManager.GetString("PublicSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unabled to read tables {0}.
        /// </summary>
        internal static string ReadingTable {
            get {
                return ResourceManager.GetString("ReadingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unabled to read companys users.
        /// </summary>
        internal static string ReadingUsers {
            get {
                return ResourceManager.GetString("ReadingUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceObjects.
        /// </summary>
        internal static string ReferenceObjects {
            get {
                return ResourceManager.GetString("ReferenceObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart of {0}.
        /// </summary>
        internal static string RestartService {
            get {
                return ResourceManager.GetString("RestartService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning! An error occured during the save of traced data!.
        /// </summary>
        internal static string SavingTracedData {
            get {
                return ResourceManager.GetString("SavingTracedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure for start scheduling activities is running.
        /// </summary>
        internal static string SchedulerStarted {
            get {
                return ResourceManager.GetString("SchedulerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The procedure for start scheduling activities is not running.
        /// </summary>
        internal static string SchedulerStopped {
            get {
                return ResourceManager.GetString("SchedulerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server.
        /// </summary>
        internal static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sections.
        /// </summary>
        internal static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is possible to associate each user with one or more functionality listed below. .
        /// </summary>
        internal static string SetArticles {
            get {
                return ResourceManager.GetString("SetArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings Admin.
        /// </summary>
        internal static string SettingsAdmin {
            get {
                return ResourceManager.GetString("SettingsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a company and a table from the following list to view in the grid the current locks detail..
        /// </summary>
        internal static string SubTitleViewCompaniesLocks {
            get {
                return ResourceManager.GetString("SubTitleViewCompaniesLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationServers used by EasyLook .
        /// </summary>
        internal static string SubTitleViewTbForEasyLook {
            get {
                return ResourceManager.GetString("SubTitleViewTbForEasyLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of users&apos; activities on used application. It is possibile to export data in Xml format .
        /// </summary>
        internal static string SubTitleViewTrace {
            get {
                return ResourceManager.GetString("SubTitleViewTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the user/users from the following list you want to disconnect from the application..
        /// </summary>
        internal static string SubTitleViewUsersConnected {
            get {
                return ResourceManager.GetString("SubTitleViewUsersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a user and a company from the following list to view in the grid the current locks detail..
        /// </summary>
        internal static string SubTitleViewUsersLocks {
            get {
                return ResourceManager.GetString("SubTitleViewUsersLocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save of traced data completed successfully !.
        /// </summary>
        internal static string SuccessXmlSaved {
            get {
                return ResourceManager.GetString("SuccessXmlSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Information.
        /// </summary>
        internal static string SystemInformations {
            get {
                return ResourceManager.GetString("SystemInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Parameters.
        /// </summary>
        internal static string SystemParameters {
            get {
                return ResourceManager.GetString("SystemParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        internal static string TableContainers {
            get {
                return ResourceManager.GetString("TableContainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableElement {
            get {
                return ResourceManager.GetString("TableElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableHeader {
            get {
                return ResourceManager.GetString("TableHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TBLoader.
        /// </summary>
        internal static string TbLoaderProcess {
            get {
                return ResourceManager.GetString("TbLoaderProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TbLoader unkillable..
        /// </summary>
        internal static string TbUnKillable {
            get {
                return ResourceManager.GetString("TbUnKillable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thread.
        /// </summary>
        internal static string Thread {
            get {
                return ResourceManager.GetString("Thread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric Identifier: {0}.
        /// </summary>
        internal static string ThreadId {
            get {
                return ResourceManager.GetString("ThreadId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event logs.
        /// </summary>
        internal static string TitleViewLogs {
            get {
                return ResourceManager.GetString("TitleViewLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLook ApplicationServers.
        /// </summary>
        internal static string TitleViewTbForEasyLook {
            get {
                return ResourceManager.GetString("TitleViewTbForEasyLook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations trace.
        /// </summary>
        internal static string TitleViewTrace {
            get {
                return ResourceManager.GetString("TitleViewTrace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected users.
        /// </summary>
        internal static string TitleViewUsersConnected {
            get {
                return ResourceManager.GetString("TitleViewUsersConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save of traced data.
        /// </summary>
        internal static string TitleXmlTraceExport {
            get {
                return ResourceManager.GetString("TitleXmlTraceExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot date is wrong! (finish date is shorter than start date).
        /// </summary>
        internal static string ToDateWrong {
            get {
                return ResourceManager.GetString("ToDateWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens Log Viewer.
        /// </summary>
        internal static string ToolTipLogViewer {
            get {
                return ResourceManager.GetString("ToolTipLogViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Parameters Management.
        /// </summary>
        internal static string ToolTipString {
            get {
                return ResourceManager.GetString("ToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string ToolTipWebServiceDetail {
            get {
                return ResourceManager.GetString("ToolTipWebServiceDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Restart service.
        /// </summary>
        internal static string ToolTipWebServiceRestart {
            get {
                return ResourceManager.GetString("ToolTipWebServiceRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the current state of web services.
        /// </summary>
        internal static string ToolTipWebServices {
            get {
                return ResourceManager.GetString("ToolTipWebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserHeader {
            get {
                return ResourceManager.GetString("UserHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected Users.
        /// </summary>
        internal static string UsersGroup {
            get {
                return ResourceManager.GetString("UsersGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting ...
        /// </summary>
        internal static string Waiting {
            get {
                return ResourceManager.GetString("Waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to clear ALL entries in MA Server EventLog?.
        /// </summary>
        internal static string WarnClearEntriesInEventLog {
            get {
                return ResourceManager.GetString("WarnClearEntriesInEventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: one or more users are connected to the application. Unable to access to this functionality..
        /// </summary>
        internal static string WarnExistLoggedUsers {
            get {
                return ResourceManager.GetString("WarnExistLoggedUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Service.
        /// </summary>
        internal static string WebServiceName {
            get {
                return ResourceManager.GetString("WebServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation&apos;s Path.
        /// </summary>
        internal static string WebServicePath {
            get {
                return ResourceManager.GetString("WebServicePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Services.
        /// </summary>
        internal static string WebServices {
            get {
                return ResourceManager.GetString("WebServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string WebServiceState {
            get {
                return ResourceManager.GetString("WebServiceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop service.
        /// </summary>
        internal static string WebServiceStop {
            get {
                return ResourceManager.GetString("WebServiceStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NT User.
        /// </summary>
        internal static string WinUser {
            get {
                return ResourceManager.GetString("WinUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to clear {0} structure because synchronization process is running! Please try again in a few minutes..
        /// </summary>
        internal static string WSClearStructureWithError {
            get {
                return ResourceManager.GetString("WSClearStructureWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} structure clearing successfully completed!.
        /// </summary>
        internal static string WSClearStructureWithSuccess {
            get {
                return ResourceManager.GetString("WSClearStructureWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load events log for {0}..
        /// </summary>
        internal static string WSEventLogUnavailable {
            get {
                return ResourceManager.GetString("WSEventLogUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize {0} web service! Please try again in a few minutes..
        /// </summary>
        internal static string WSInitWithError {
            get {
                return ResourceManager.GetString("WSInitWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} web service initializing successfully completed!.
        /// </summary>
        internal static string WSInitWithSuccess {
            get {
                return ResourceManager.GetString("WSInitWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to stop {0} service because synchronization process is running! Please try again in a few minutes..
        /// </summary>
        internal static string WSStopServiceWithError {
            get {
                return ResourceManager.GetString("WSStopServiceWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} stopping successfully completed!.
        /// </summary>
        internal static string WSStopServiceWithSuccess {
            get {
                return ResourceManager.GetString("WSStopServiceWithSuccess", resourceCulture);
            }
        }
    }
}
