//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationService.BBServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowContext", Namespace="http://schemas.datacontract.org/2004/07/PAT.Workflow.Runtime.Services")]
    [System.SerializableAttribute()]
    public partial class WorkflowContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationConnectionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationProviderEventIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ApplicationProviderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> ParametersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationConnectionCode {
            get {
                return this.ApplicationConnectionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationConnectionCodeField, value) != true)) {
                    this.ApplicationConnectionCodeField = value;
                    this.RaisePropertyChanged("ApplicationConnectionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationProviderEventID {
            get {
                return this.ApplicationProviderEventIDField;
            }
            set {
                if ((this.ApplicationProviderEventIDField.Equals(value) != true)) {
                    this.ApplicationProviderEventIDField = value;
                    this.RaisePropertyChanged("ApplicationProviderEventID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationProviderID {
            get {
                return this.ApplicationProviderIDField;
            }
            set {
                if ((this.ApplicationProviderIDField.Equals(value) != true)) {
                    this.ApplicationProviderIDField = value;
                    this.RaisePropertyChanged("ApplicationProviderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchemaMetadata", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta")]
    [System.SerializableAttribute()]
    public partial class SchemaMetadata : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.LayoutGroup RootField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int mVersionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.LayoutGroup Root {
            get {
                return this.RootField;
            }
            set {
                if ((object.ReferenceEquals(this.RootField, value) != true)) {
                    this.RootField = value;
                    this.RaisePropertyChanged("Root");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int mVersion {
            get {
                return this.mVersionField;
            }
            set {
                if ((this.mVersionField.Equals(value) != true)) {
                    this.mVersionField = value;
                    this.RaisePropertyChanged("mVersion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutGroup", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    public partial class LayoutGroup : NotificationService.BBServiceReference.LayoutItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BorderVisibleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.LayoutItems ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.LayoutType LayoutTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BorderVisible {
            get {
                return this.BorderVisibleField;
            }
            set {
                if ((this.BorderVisibleField.Equals(value) != true)) {
                    this.BorderVisibleField = value;
                    this.RaisePropertyChanged("BorderVisible");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caption {
            get {
                return this.CaptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CaptionField, value) != true)) {
                    this.CaptionField = value;
                    this.RaisePropertyChanged("Caption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.LayoutItems Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.LayoutType LayoutType {
            get {
                return this.LayoutTypeField;
            }
            set {
                if ((this.LayoutTypeField.Equals(value) != true)) {
                    this.LayoutTypeField = value;
                    this.RaisePropertyChanged("LayoutType");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="APMObject", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ListItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.EmptySpace))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.AbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDown))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Text))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DateEdit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Label))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Button))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItemField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    public partial class APMObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListItem", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.SchemaMetadata))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.EmptySpace))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDown))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.AbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Text))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DateEdit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Label))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Button))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FieldTypeEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FieldValidation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ListItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItems))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItemField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ConnectionReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.APMObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Guid[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ApplicationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkFlowInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FormInstanceInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FormInstanceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.MilestoneInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.MilestoneInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkFlowInfo[]))]
    public partial class ListItem : NotificationService.BBServiceReference.APMObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAbstractControl", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.EmptySpace))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.AbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDown))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Text))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DateEdit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Label))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Button))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItemField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    public partial class BaseAbstractControl : NotificationService.BBServiceReference.APMObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FieldName {
            get {
                return this.FieldNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldNameField, value) != true)) {
                    this.FieldNameField = value;
                    this.RaisePropertyChanged("FieldName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmptySpace", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EmptySpace : NotificationService.BBServiceReference.BaseAbstractControl {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseAbstractField", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.AbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDown))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Text))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DateEdit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Label))]
    public partial class BaseAbstractField : NotificationService.BBServiceReference.BaseAbstractControl {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractField", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDown))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Text))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DateEdit))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.SchemaMetadata))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractControl))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.EmptySpace))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.BaseAbstractField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Label))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.Button))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FieldTypeEnum))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FieldValidation))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ListItem[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ListItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItems))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItemField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutType))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ConnectionReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowStatus))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.APMObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowStatus[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Collections.Generic.Dictionary<string, object>))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Guid[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkflowContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.ApplicationContext))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkFlowInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FormInstanceInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.FormInstanceInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.MilestoneInfo[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.MilestoneInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.WorkFlowInfo[]))]
    public partial class AbstractField : NotificationService.BBServiceReference.BaseAbstractField {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.FieldTypeEnum FieldTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsMandatoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsReadOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.FieldValidation ValidationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.FieldTypeEnum FieldType {
            get {
                return this.FieldTypeField;
            }
            set {
                if ((this.FieldTypeField.Equals(value) != true)) {
                    this.FieldTypeField = value;
                    this.RaisePropertyChanged("FieldType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsMandatory {
            get {
                return this.IsMandatoryField;
            }
            set {
                if ((this.IsMandatoryField.Equals(value) != true)) {
                    this.IsMandatoryField = value;
                    this.RaisePropertyChanged("IsMandatory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReadOnly {
            get {
                return this.IsReadOnlyField;
            }
            set {
                if ((this.IsReadOnlyField.Equals(value) != true)) {
                    this.IsReadOnlyField = value;
                    this.RaisePropertyChanged("IsReadOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label {
            get {
                return this.LabelField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelField, value) != true)) {
                    this.LabelField = value;
                    this.RaisePropertyChanged("Label");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.FieldValidation Validation {
            get {
                return this.ValidationField;
            }
            set {
                if ((object.ReferenceEquals(this.ValidationField, value) != true)) {
                    this.ValidationField = value;
                    this.RaisePropertyChanged("Validation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DropDown", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.DropDownMultiple))]
    public partial class DropDown : NotificationService.BBServiceReference.AbstractField {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.ListItem[] ItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.ListItem[] Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DropDownMultiple", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DropDownMultiple : NotificationService.BBServiceReference.DropDown {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Text", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Text : NotificationService.BBServiceReference.AbstractField {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte LinesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((this.LinesField.Equals(value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DateEdit", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class DateEdit : NotificationService.BBServiceReference.AbstractField {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Label", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Label : NotificationService.BBServiceReference.BaseAbstractField {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LabelMemberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="Label")]
        public string LabelMember {
            get {
                return this.LabelMemberField;
            }
            set {
                if ((object.ReferenceEquals(this.LabelMemberField, value) != true)) {
                    this.LabelMemberField = value;
                    this.RaisePropertyChanged("LabelMember");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Button", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Button : NotificationService.BBServiceReference.BaseAbstractControl {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutItem", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutItemField))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutGroup))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotificationService.BBServiceReference.LayoutTabbedGroup))]
    public partial class LayoutItem : NotificationService.BBServiceReference.BaseAbstractControl {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ShowTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ShowText {
            get {
                return this.ShowTextField;
            }
            set {
                if ((this.ShowTextField.Equals(value) != true)) {
                    this.ShowTextField = value;
                    this.RaisePropertyChanged("ShowText");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutItemField", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class LayoutItemField : NotificationService.BBServiceReference.LayoutItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.BaseAbstractControl FieldField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.BaseAbstractControl Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutTabbedGroup", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class LayoutTabbedGroup : NotificationService.BBServiceReference.LayoutGroup {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefaultTabField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultTab {
            get {
                return this.DefaultTabField;
            }
            set {
                if ((this.DefaultTabField.Equals(value) != true)) {
                    this.DefaultTabField = value;
                    this.RaisePropertyChanged("DefaultTab");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="LayoutItems", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta", ItemName="LayoutItem")]
    [System.SerializableAttribute()]
    public class LayoutItems : System.Collections.Generic.List<NotificationService.BBServiceReference.LayoutItem> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LayoutType", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta")]
    public enum LayoutType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vertical = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Horizontal = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldTypeEnum", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta")]
    public enum FieldTypeEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        String = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Byte = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Integer = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Long = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Double = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Date = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DateTime = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Boolean = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FieldValidation", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects.Forms.Metada" +
        "ta")]
    [System.SerializableAttribute()]
    public partial class FieldValidation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegExField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RegEx {
            get {
                return this.RegExField;
            }
            set {
                if ((object.ReferenceEquals(this.RegExField, value) != true)) {
                    this.RegExField = value;
                    this.RaisePropertyChanged("RegEx");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionReference", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects")]
    [System.SerializableAttribute()]
    public partial class ConnectionReference : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid _ApplicationProviderIDField;
        
        private string _CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid _ApplicationProviderID {
            get {
                return this._ApplicationProviderIDField;
            }
            set {
                if ((this._ApplicationProviderIDField.Equals(value) != true)) {
                    this._ApplicationProviderIDField = value;
                    this.RaisePropertyChanged("_ApplicationProviderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string _Code {
            get {
                return this._CodeField;
            }
            set {
                if ((object.ReferenceEquals(this._CodeField, value) != true)) {
                    this._CodeField = value;
                    this.RaisePropertyChanged("_Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowStatus", Namespace="http://schemas.datacontract.org/2004/07/PAT.CRM.WSC4.WorkflowObjects")]
    public enum WorkflowStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pending = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scheduled = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Running = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Completed = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Canceled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resumable = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = -1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ApplicationContext", Namespace="http://schemas.datacontract.org/2004/07/PAT.Workflow.Runtime.Services")]
    [System.SerializableAttribute()]
    public partial class ApplicationContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsernameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectIDField, value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType {
            get {
                return this.ObjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectTypeField, value) != true)) {
                    this.ObjectTypeField = value;
                    this.RaisePropertyChanged("ObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username {
            get {
                return this.UsernameField;
            }
            set {
                if ((object.ReferenceEquals(this.UsernameField, value) != true)) {
                    this.UsernameField = value;
                    this.RaisePropertyChanged("Username");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkFlowInfo", Namespace="http://schemas.datacontract.org/2004/07/PAT.Workflow.Runtime.Services")]
    [System.SerializableAttribute()]
    public partial class WorkFlowInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCompletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateLastUpdatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateStartedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DefinitionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExistsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.FormInstanceInfo[] FormInstancesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.MilestoneInfo[] MilestonesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObjectTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WorkFlowIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private NotificationService.BBServiceReference.WorkflowStatus WorkflowStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCompleted {
            get {
                return this.DateCompletedField;
            }
            set {
                if ((this.DateCompletedField.Equals(value) != true)) {
                    this.DateCompletedField = value;
                    this.RaisePropertyChanged("DateCompleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateLastUpdated {
            get {
                return this.DateLastUpdatedField;
            }
            set {
                if ((this.DateLastUpdatedField.Equals(value) != true)) {
                    this.DateLastUpdatedField = value;
                    this.RaisePropertyChanged("DateLastUpdated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateStarted {
            get {
                return this.DateStartedField;
            }
            set {
                if ((this.DateStartedField.Equals(value) != true)) {
                    this.DateStartedField = value;
                    this.RaisePropertyChanged("DateStarted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DefinitionID {
            get {
                return this.DefinitionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.DefinitionIDField, value) != true)) {
                    this.DefinitionIDField = value;
                    this.RaisePropertyChanged("DefinitionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exists {
            get {
                return this.ExistsField;
            }
            set {
                if ((this.ExistsField.Equals(value) != true)) {
                    this.ExistsField = value;
                    this.RaisePropertyChanged("Exists");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.FormInstanceInfo[] FormInstances {
            get {
                return this.FormInstancesField;
            }
            set {
                if ((object.ReferenceEquals(this.FormInstancesField, value) != true)) {
                    this.FormInstancesField = value;
                    this.RaisePropertyChanged("FormInstances");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.MilestoneInfo[] Milestones {
            get {
                return this.MilestonesField;
            }
            set {
                if ((object.ReferenceEquals(this.MilestonesField, value) != true)) {
                    this.MilestonesField = value;
                    this.RaisePropertyChanged("Milestones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Note {
            get {
                return this.NoteField;
            }
            set {
                if ((object.ReferenceEquals(this.NoteField, value) != true)) {
                    this.NoteField = value;
                    this.RaisePropertyChanged("Note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectID {
            get {
                return this.ObjectIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectIDField, value) != true)) {
                    this.ObjectIDField = value;
                    this.RaisePropertyChanged("ObjectID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ObjectType {
            get {
                return this.ObjectTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectTypeField, value) != true)) {
                    this.ObjectTypeField = value;
                    this.RaisePropertyChanged("ObjectType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorkFlowID {
            get {
                return this.WorkFlowIDField;
            }
            set {
                if ((this.WorkFlowIDField.Equals(value) != true)) {
                    this.WorkFlowIDField = value;
                    this.RaisePropertyChanged("WorkFlowID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotificationService.BBServiceReference.WorkflowStatus WorkflowStatus {
            get {
                return this.WorkflowStatusField;
            }
            set {
                if ((this.WorkflowStatusField.Equals(value) != true)) {
                    this.WorkflowStatusField = value;
                    this.RaisePropertyChanged("WorkflowStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormInstanceInfo", Namespace="http://schemas.datacontract.org/2004/07/PAT.Workflow.Runtime.Services")]
    [System.SerializableAttribute()]
    public partial class FormInstanceInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateProcessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateSubmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FormInstanceIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool NotificationOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ProcessedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid WorkFlowIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateProcessed {
            get {
                return this.DateProcessedField;
            }
            set {
                if ((this.DateProcessedField.Equals(value) != true)) {
                    this.DateProcessedField = value;
                    this.RaisePropertyChanged("DateProcessed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateSubmitted {
            get {
                return this.DateSubmittedField;
            }
            set {
                if ((this.DateSubmittedField.Equals(value) != true)) {
                    this.DateSubmittedField = value;
                    this.RaisePropertyChanged("DateSubmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FormInstanceID {
            get {
                return this.FormInstanceIDField;
            }
            set {
                if ((this.FormInstanceIDField.Equals(value) != true)) {
                    this.FormInstanceIDField = value;
                    this.RaisePropertyChanged("FormInstanceID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool NotificationOnly {
            get {
                return this.NotificationOnlyField;
            }
            set {
                if ((this.NotificationOnlyField.Equals(value) != true)) {
                    this.NotificationOnlyField = value;
                    this.RaisePropertyChanged("NotificationOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Processed {
            get {
                return this.ProcessedField;
            }
            set {
                if ((this.ProcessedField.Equals(value) != true)) {
                    this.ProcessedField = value;
                    this.RaisePropertyChanged("Processed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid WorkFlowID {
            get {
                return this.WorkFlowIDField;
            }
            set {
                if ((this.WorkFlowIDField.Equals(value) != true)) {
                    this.WorkFlowIDField = value;
                    this.RaisePropertyChanged("WorkFlowID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MilestoneInfo", Namespace="http://schemas.datacontract.org/2004/07/PAT.Workflow.Runtime.Services")]
    [System.SerializableAttribute()]
    public partial class MilestoneInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MilestoneIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ParametersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MilestoneID {
            get {
                return this.MilestoneIDField;
            }
            set {
                if ((this.MilestoneIDField.Equals(value) != true)) {
                    this.MilestoneIDField = value;
                    this.RaisePropertyChanged("MilestoneID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Parameters {
            get {
                return this.ParametersField;
            }
            set {
                if ((object.ReferenceEquals(this.ParametersField, value) != true)) {
                    this.ParametersField = value;
                    this.RaisePropertyChanged("Parameters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tag {
            get {
                return this.TagField;
            }
            set {
                if ((object.ReferenceEquals(this.TagField, value) != true)) {
                    this.TagField = value;
                    this.RaisePropertyChanged("Tag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BBServiceReference.IWorkflowService")]
    public interface IWorkflowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/Ping", ReplyAction="http://tempuri.org/IWorkflowService/PingResponse")]
        bool Ping();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/DispatchEvent", ReplyAction="http://tempuri.org/IWorkflowService/DispatchEventResponse")]
        void DispatchEvent(NotificationService.BBServiceReference.WorkflowContext Context);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/DispatchEventForDefinition", ReplyAction="http://tempuri.org/IWorkflowService/DispatchEventForDefinitionResponse")]
        System.Guid DispatchEventForDefinition(NotificationService.BBServiceReference.WorkflowContext Context, int DefinitionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/DispatchEventForDefinitionByIdentifier", ReplyAction="http://tempuri.org/IWorkflowService/DispatchEventForDefinitionByIdentifierRespons" +
            "e")]
        System.Guid DispatchEventForDefinitionByIdentifier(NotificationService.BBServiceReference.WorkflowContext Context, System.Guid DefinitionIdentifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/ArchiveOldWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/ArchiveOldWorkflowsResponse")]
        int ArchiveOldWorkflows(System.TimeSpan span);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/RemoveArchivedWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/RemoveArchivedWorkflowsResponse")]
        int RemoveArchivedWorkflows(System.TimeSpan span);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/TerminateWorkflow", ReplyAction="http://tempuri.org/IWorkflowService/TerminateWorkflowResponse")]
        bool TerminateWorkflow(System.Guid InstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/CancelWorkflow", ReplyAction="http://tempuri.org/IWorkflowService/CancelWorkflowResponse")]
        bool CancelWorkflow(System.Guid InstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/RestartWorkflow", ReplyAction="http://tempuri.org/IWorkflowService/RestartWorkflowResponse")]
        bool RestartWorkflow(System.Guid InstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/TerminateWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/TerminateWorkflowsResponse")]
        bool TerminateWorkflows(System.Guid[] InstanceIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/CancelWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/CancelWorkflowsResponse")]
        bool CancelWorkflows(System.Guid[] InstanceIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/RestartWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/RestartWorkflowsResponse")]
        bool RestartWorkflows(System.Guid[] InstanceIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/ResumeBookmark", ReplyAction="http://tempuri.org/IWorkflowService/ResumeBookmarkResponse")]
        bool ResumeBookmark(System.Guid InstanceID, string BookmarkName, System.Collections.Generic.Dictionary<string, object> BookmarkContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/ResumeBookmarkByExternalCorrelationID", ReplyAction="http://tempuri.org/IWorkflowService/ResumeBookmarkByExternalCorrelationIDResponse" +
            "")]
        bool ResumeBookmarkByExternalCorrelationID(string CorrelationID, System.Collections.Generic.Dictionary<string, object> BookmarkContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/CreateWorkflow", ReplyAction="http://tempuri.org/IWorkflowService/CreateWorkflowResponse")]
        System.Guid CreateWorkflow(NotificationService.BBServiceReference.WorkflowContext Context, System.Guid DefinitionIdentifier, NotificationService.BBServiceReference.ApplicationContext AppContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/Subscribe", ReplyAction="http://tempuri.org/IWorkflowService/SubscribeResponse")]
        bool Subscribe(System.Guid WorkflowID, string Username, string NotificationURL);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/UnSubscribe", ReplyAction="http://tempuri.org/IWorkflowService/UnSubscribeResponse")]
        bool UnSubscribe(System.Guid WorkflowID, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetWorkFlowInfo", ReplyAction="http://tempuri.org/IWorkflowService/GetWorkFlowInfoResponse")]
        NotificationService.BBServiceReference.WorkFlowInfo GetWorkFlowInfo(System.Guid WorkflowID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetWorkFlowsInfo", ReplyAction="http://tempuri.org/IWorkflowService/GetWorkFlowsInfoResponse")]
        NotificationService.BBServiceReference.WorkFlowInfo[] GetWorkFlowsInfo(string ObjectType, string ObjectID, string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetFormSchema", ReplyAction="http://tempuri.org/IWorkflowService/GetFormSchemaResponse")]
        NotificationService.BBServiceReference.SchemaMetadata GetFormSchema(int FormInstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/SetFormSchema", ReplyAction="http://tempuri.org/IWorkflowService/SetFormSchemaResponse")]
        bool SetFormSchema(NotificationService.BBServiceReference.SchemaMetadata SchemaMetadata, int FormInstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetFormInstances", ReplyAction="http://tempuri.org/IWorkflowService/GetFormInstancesResponse")]
        NotificationService.BBServiceReference.FormInstanceInfo[] GetFormInstances(string Username, bool IncludeProcessed);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetFormInstance", ReplyAction="http://tempuri.org/IWorkflowService/GetFormInstanceResponse")]
        NotificationService.BBServiceReference.FormInstanceInfo GetFormInstance(int FormInstanceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetPendingFormInstanceCount", ReplyAction="http://tempuri.org/IWorkflowService/GetPendingFormInstanceCountResponse")]
        int GetPendingFormInstanceCount(string Username);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkflowService/GetWorkflows", ReplyAction="http://tempuri.org/IWorkflowService/GetWorkflowsResponse")]
        NotificationService.BBServiceReference.WorkFlowInfo[] GetWorkflows(string Username, NotificationService.BBServiceReference.WorkflowStatus[] WorkflowStatus, string EntityID, string ObjectID, int maxRecords);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkflowServiceChannel : NotificationService.BBServiceReference.IWorkflowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkflowServiceClient : System.ServiceModel.ClientBase<NotificationService.BBServiceReference.IWorkflowService>, NotificationService.BBServiceReference.IWorkflowService {
        
        public WorkflowServiceClient() {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkflowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Ping() {
            return base.Channel.Ping();
        }
        
        public void DispatchEvent(NotificationService.BBServiceReference.WorkflowContext Context) {
            base.Channel.DispatchEvent(Context);
        }
        
        public System.Guid DispatchEventForDefinition(NotificationService.BBServiceReference.WorkflowContext Context, int DefinitionID) {
            return base.Channel.DispatchEventForDefinition(Context, DefinitionID);
        }
        
        public System.Guid DispatchEventForDefinitionByIdentifier(NotificationService.BBServiceReference.WorkflowContext Context, System.Guid DefinitionIdentifier) {
            return base.Channel.DispatchEventForDefinitionByIdentifier(Context, DefinitionIdentifier);
        }
        
        public int ArchiveOldWorkflows(System.TimeSpan span) {
            return base.Channel.ArchiveOldWorkflows(span);
        }
        
        public int RemoveArchivedWorkflows(System.TimeSpan span) {
            return base.Channel.RemoveArchivedWorkflows(span);
        }
        
        public bool TerminateWorkflow(System.Guid InstanceID) {
            return base.Channel.TerminateWorkflow(InstanceID);
        }
        
        public bool CancelWorkflow(System.Guid InstanceID) {
            return base.Channel.CancelWorkflow(InstanceID);
        }
        
        public bool RestartWorkflow(System.Guid InstanceID) {
            return base.Channel.RestartWorkflow(InstanceID);
        }
        
        public bool TerminateWorkflows(System.Guid[] InstanceIDs) {
            return base.Channel.TerminateWorkflows(InstanceIDs);
        }
        
        public bool CancelWorkflows(System.Guid[] InstanceIDs) {
            return base.Channel.CancelWorkflows(InstanceIDs);
        }
        
        public bool RestartWorkflows(System.Guid[] InstanceIDs) {
            return base.Channel.RestartWorkflows(InstanceIDs);
        }
        
        public bool ResumeBookmark(System.Guid InstanceID, string BookmarkName, System.Collections.Generic.Dictionary<string, object> BookmarkContext) {
            return base.Channel.ResumeBookmark(InstanceID, BookmarkName, BookmarkContext);
        }
        
        public bool ResumeBookmarkByExternalCorrelationID(string CorrelationID, System.Collections.Generic.Dictionary<string, object> BookmarkContext) {
            return base.Channel.ResumeBookmarkByExternalCorrelationID(CorrelationID, BookmarkContext);
        }
        
        public System.Guid CreateWorkflow(NotificationService.BBServiceReference.WorkflowContext Context, System.Guid DefinitionIdentifier, NotificationService.BBServiceReference.ApplicationContext AppContext) {
            return base.Channel.CreateWorkflow(Context, DefinitionIdentifier, AppContext);
        }
        
        public bool Subscribe(System.Guid WorkflowID, string Username, string NotificationURL) {
            return base.Channel.Subscribe(WorkflowID, Username, NotificationURL);
        }
        
        public bool UnSubscribe(System.Guid WorkflowID, string Username) {
            return base.Channel.UnSubscribe(WorkflowID, Username);
        }
        
        public NotificationService.BBServiceReference.WorkFlowInfo GetWorkFlowInfo(System.Guid WorkflowID) {
            return base.Channel.GetWorkFlowInfo(WorkflowID);
        }
        
        public NotificationService.BBServiceReference.WorkFlowInfo[] GetWorkFlowsInfo(string ObjectType, string ObjectID, string Username) {
            return base.Channel.GetWorkFlowsInfo(ObjectType, ObjectID, Username);
        }
        
        public NotificationService.BBServiceReference.SchemaMetadata GetFormSchema(int FormInstanceID) {
            return base.Channel.GetFormSchema(FormInstanceID);
        }
        
        public bool SetFormSchema(NotificationService.BBServiceReference.SchemaMetadata SchemaMetadata, int FormInstanceID) {
            return base.Channel.SetFormSchema(SchemaMetadata, FormInstanceID);
        }
        
        public NotificationService.BBServiceReference.FormInstanceInfo[] GetFormInstances(string Username, bool IncludeProcessed) {
            return base.Channel.GetFormInstances(Username, IncludeProcessed);
        }
        
        public NotificationService.BBServiceReference.FormInstanceInfo GetFormInstance(int FormInstanceID) {
            return base.Channel.GetFormInstance(FormInstanceID);
        }
        
        public int GetPendingFormInstanceCount(string Username) {
            return base.Channel.GetPendingFormInstanceCount(Username);
        }
        
        public NotificationService.BBServiceReference.WorkFlowInfo[] GetWorkflows(string Username, NotificationService.BBServiceReference.WorkflowStatus[] WorkflowStatus, string EntityID, string ObjectID, int maxRecords) {
            return base.Channel.GetWorkflows(Username, WorkflowStatus, EntityID, ObjectID, maxRecords);
        }
    }
}
