dotnet restore ../server/library/PDFSharpCore/PDFSharpCore.csproj --no-cache
dotnet restore ../server/library/taskbuilder-netcore-interfaces/taskbuilder-netcore-interfaces.csproj --no-cache
dotnet restore ../server/library/taskbuilder-netcore-data/taskbuilder-netcore-data.csproj --no-cache
dotnet restore ../server/library/taskbuilder-netcore-data-functionality/taskbuilder-netcore-data-functionality.csproj --no-cache
dotnet restore ../server/library/taskbuilder-netcore-common/taskbuilder-netcore-common.csproj --no-cache
dotnet restore ../server/account-manager/account-manager.csproj --no-cache
dotnet restore ../server/provisioning-server/provisioning-server.csproj --no-cache
dotnet restore ../server/menu-gate/menu-gate.csproj --no-cache
dotnet restore ../server/data-service/data-service.csproj --no-cache
dotnet restore ../server/database-service/database-service.csproj --no-cache
dotnet restore ../server/rs-web/rs-web.csproj --no-cache
dotnet restore ../server/tbloader-gate/tbloader-gate.csproj --no-cache
dotnet restore ../server/web-server/web-server.csproj --no-cache
dotnet restore ../server/widgets-service/widgets-service.csproj --no-cache
dotnet restore ../server/manufacturing-service/manufacturing-service.csproj --no-cache
dotnet restore ../server/licensing-manager/licensing-manager.csproj --no-cache