dotnet restore ../server/library/PDFSharpCore/project.json --no-cache
dotnet restore ../server/library/taskbuilder-netcore-interfaces/project.json --no-cache
dotnet restore ../server/library/taskbuilder-netcore-data/project.json --no-cache
dotnet restore ../server/library/taskbuilder-netcore-data-functionality/project.json --no-cache
dotnet restore ../server/library/taskbuilder-netcore-common/project.json --no-cache
dotnet restore ../server/account-manager/project.json --no-cache
dotnet restore ../server/provisioning-server/project.json --no-cache
dotnet restore ../server/menu-gate/project.json --no-cache
dotnet restore ../server/data-service/project.json --no-cache
dotnet restore ../server/database-service/project.json --no-cache
dotnet restore ../server/rs-web/project.json --no-cache
dotnet restore ../server/tbloader-gate/project.json --no-cache
dotnet restore ../server/web-server/project.json --no-cache
dotnet restore ../server/widgets-service/project.json --no-cache
dotnet restore ../server/manufacturing-service/project.json --no-cache