//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.Console.Plugin.AuditingAdmin {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microarea.Console.Plugin.AuditingAdmin.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traced tables.
        /// </summary>
        internal static string AllTablesLabel {
            get {
                return ResourceManager.GetString("AllTablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application name.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traced tables of application {0}.
        /// </summary>
        internal static string ApplicationTablesLabel {
            get {
                return ResourceManager.GetString("ApplicationTablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing management.
        /// </summary>
        internal static string AuditTableManagerTitle {
            get {
                return ResourceManager.GetString("AuditTableManagerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The columns to traced of table {0} has been modified. Do you want to apply the changes?.
        /// </summary>
        internal static string ChangeConfirmation {
            get {
                return ResourceManager.GetString("ChangeConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change key.
        /// </summary>
        internal static string ChangeKey {
            get {
                return ResourceManager.GetString("ChangeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name.
        /// </summary>
        internal static string ColumnName {
            get {
                return ResourceManager.GetString("ColumnName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        internal static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string ConfirmationTitle {
            get {
                return ResourceManager.GetString("ConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to connect to company database {0}. Check its correctness..
        /// </summary>
        internal static string ConnectError {
            get {
                return ResourceManager.GetString("ConnectError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete query data.
        /// </summary>
        internal static string DeleteBtnToolTip {
            get {
                return ResourceManager.GetString("DeleteBtnToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete traced data extracted?.
        /// </summary>
        internal static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselect all.
        /// </summary>
        internal static string DeselectAll {
            get {
                return ResourceManager.GetString("DeselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error during synonym creation.
        /// </summary>
        internal static string ErrCreatingSynonym {
            get {
                return ResourceManager.GetString("ErrCreatingSynonym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to During execution of query {0} occurred the following error.
        /// </summary>
        internal static string ExecuteQueryError {
            get {
                return ResourceManager.GetString("ExecuteQueryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter rules.
        /// </summary>
        internal static string FilterTitle {
            get {
                return ResourceManager.GetString("FilterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert tracing for selected table..
        /// </summary>
        internal static string InsertDescription {
            get {
                return ResourceManager.GetString("InsertDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert on tracing.
        /// </summary>
        internal static string InsertInAuditing {
            get {
                return ResourceManager.GetString("InsertInAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading company database design.
        /// </summary>
        internal static string LoadDatabaseInfo {
            get {
                return ResourceManager.GetString("LoadDatabaseInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete confirm.
        /// </summary>
        internal static string MakeDelete {
            get {
                return ResourceManager.GetString("MakeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name.
        /// </summary>
        internal static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traced tables of module {0}.
        /// </summary>
        internal static string ModuleTablesLabel {
            get {
                return ResourceManager.GetString("ModuleTablesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string NamespaceTitle {
            get {
                return ResourceManager.GetString("NamespaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose row type to display.
        /// </summary>
        internal static string NoOperationFilter {
            get {
                return ResourceManager.GetString("NoOperationFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database doesn&apos;t contain Auditing tables. Please make an update database..
        /// </summary>
        internal static string NoTables {
            get {
                return ResourceManager.GetString("NoTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not traced table.
        /// </summary>
        internal static string NoTracedStatus {
            get {
                return ResourceManager.GetString("NoTracedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected company is not valid! Perform migration with Net Migration Kit.
        /// </summary>
        internal static string NoValidCompany {
            get {
                return ResourceManager.GetString("NoValidCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation data.
        /// </summary>
        internal static string OperDataTitle {
            get {
                return ResourceManager.GetString("OperDataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation.
        /// </summary>
        internal static string OperTypeTitle {
            get {
                return ResourceManager.GetString("OperTypeTitle", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause tracing.
        /// </summary>
        internal static string PauseAuditing {
            get {
                return ResourceManager.GetString("PauseAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause temporally tracing process for selected table. Existing data will be not deleted..
        /// </summary>
        internal static string PauseDescription {
            get {
                return ResourceManager.GetString("PauseDescription", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaboration in progress....
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auditing Administrator.
        /// </summary>
        internal static string PlugInTitle {
            get {
                return ResourceManager.GetString("PlugInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query selected table using filter rules settings.
        /// </summary>
        internal static string QueryBtnToolTip {
            get {
                return ResourceManager.GetString("QueryBtnToolTip", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume tracing.
        /// </summary>
        internal static string RestartAuditing {
            get {
                return ResourceManager.GetString("RestartAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume tracing process for selected table.
        /// </summary>
        internal static string RestartDescription {
            get {
                return ResourceManager.GetString("RestartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show data.
        /// </summary>
        internal static string RunQuery {
            get {
                return ResourceManager.GetString("RunQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all.
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention: syntax incorrect!.
        /// </summary>
        internal static string SqlQueryError {
            get {
                return ResourceManager.GetString("SqlQueryError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete tracing.
        /// </summary>
        internal static string StopAuditing {
            get {
                return ResourceManager.GetString("StopAuditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete traced data and selected table from tracing process..
        /// </summary>
        internal static string StopDescription {
            get {
                return ResourceManager.GetString("StopDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suspended traced table.
        /// </summary>
        internal static string StopTraceStatus {
            get {
                return ResourceManager.GetString("StopTraceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation successfully completed.
        /// </summary>
        internal static string SuccessOperation {
            get {
                return ResourceManager.GetString("SuccessOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table name.
        /// </summary>
        internal static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status of {0} table.
        /// </summary>
        internal static string TableStatusDescri {
            get {
                return ResourceManager.GetString("TableStatusDescri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tracing administration of company data.
        /// </summary>
        internal static string ToolTipString {
            get {
                return ResourceManager.GetString("ToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traced.
        /// </summary>
        internal static string Traced {
            get {
                return ResourceManager.GetString("Traced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traced table.
        /// </summary>
        internal static string TracedStatus {
            get {
                return ResourceManager.GetString("TracedStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown operation.
        /// </summary>
        internal static string UnknownOper {
            get {
                return ResourceManager.GetString("UnknownOper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserTitle {
            get {
                return ResourceManager.GetString("UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
