//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microarea.TaskBuilderNet.Core.TbOleDbInterface
{


	[System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBHeaderInfo", Namespace="urn:Microarea.Web.Services")]
    [System.SerializableAttribute()]
    public partial class TBHeaderInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthToken {
            get {
                return this.AuthTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthTokenField, value) != true)) {
                    this.AuthTokenField = value;
                    this.RaisePropertyChanged("AuthToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
    [System.SerializableAttribute()]
    public partial class TBSoapFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:Microarea.Web.Services", ConfigurationName="TbOleDbInterface.TbOleDb")]
    public interface TbOleDb {
        
        // CODEGEN: Generating message contract since the operation SqlRecord_SetStorable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_SetStorable", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_SetStorableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_SetStorableTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableOut SqlRecord_SetStorable(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableIn request);
        
        // CODEGEN: Generating message contract since the operation SqlRecord_Copy is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_Copy", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_CopyResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_CopyTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyOut SqlRecord_Copy(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyIn request);
        
        // CODEGEN: Generating message contract since the operation GetConnection is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#GetConnection", ReplyAction="urn:Microarea.Web.Services/TbOleDb/GetConnectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/GetConnectionTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionOut GetConnection(Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionIn request);
        
        // CODEGEN: Generating message contract since the operation OpenConnection is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#OpenConnection", ReplyAction="urn:Microarea.Web.Services/TbOleDb/OpenConnectionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/OpenConnectionTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionOut OpenConnection(Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionIn request);
        
        // CODEGEN: Generating message contract since the operation CreateRecord is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#CreateRecord", ReplyAction="urn:Microarea.Web.Services/TbOleDb/CreateRecordResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/CreateRecordTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordOut CreateRecord(Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordIn request);
        
        // CODEGEN: Generating message contract since the operation Connection_Close is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#Connection_Close", ReplyAction="urn:Microarea.Web.Services/TbOleDb/Connection_CloseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/Connection_CloseTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseOut Connection_Close(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseIn request);
        
        // CODEGEN: Generating message contract since the operation Connection_BeginTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#Connection_BeginTransaction", ReplyAction="urn:Microarea.Web.Services/TbOleDb/Connection_BeginTransactionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/Connection_BeginTransactionTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionOut Connection_BeginTransaction(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionIn request);
        
        // CODEGEN: Generating message contract since the operation Connection_Commit is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#Connection_Commit", ReplyAction="urn:Microarea.Web.Services/TbOleDb/Connection_CommitResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/Connection_CommitTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitOut Connection_Commit(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitIn request);
        
        // CODEGEN: Generating message contract since the operation Connection_Rollback is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#Connection_Rollback", ReplyAction="urn:Microarea.Web.Services/TbOleDb/Connection_RollbackResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/Connection_RollbackTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackOut Connection_Rollback(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackIn request);
        
        // CODEGEN: Generating message contract since the operation GetExtraFiltering is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#GetExtraFiltering", ReplyAction="urn:Microarea.Web.Services/TbOleDb/GetExtraFilteringResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/GetExtraFilteringTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringOut GetExtraFiltering(Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringIn request);
        
        // CODEGEN: Generating message contract since the operation SqlRecord_Clone is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_Clone", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_CloneResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_CloneTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneOut SqlRecord_Clone(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneIn request);
        
        // CODEGEN: Generating message contract since the operation SqlRecord_GetFieldValue is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_GetFieldValue", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_GetFieldValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_GetFieldValueTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueOut SqlRecord_GetFieldValue(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueIn request);
        
        // CODEGEN: Generating message contract since the operation SqlRecord_SetFieldValue is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_SetFieldValue", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_SetFieldValueResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_SetFieldValueTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueOut SqlRecord_SetFieldValue(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueIn request);
        
        // CODEGEN: Generating message contract since the operation SqlRecord_IsStorable is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="#SqlRecord_IsStorable", ReplyAction="urn:Microarea.Web.Services/TbOleDb/SqlRecord_IsStorableResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBSoapFault), Action="urn:Microarea.Web.Services/TbOleDb/SqlRecord_IsStorableTBSoapFaultFault", Name="TBSoapFault", Namespace="http://schemas.datacontract.org/2004/07/Microarea.TaskBuilderNet.Core.SoapCall")]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableOut SqlRecord_IsStorable(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableIn request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_SetStorableIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_SetStorable", Order=0)]
        public int handle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_SetStorable", Order=1)]
        public bool bStorable;
        
        public SqlRecord_SetStorableIn() {
        }
        
        public SqlRecord_SetStorableIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, bool bStorable) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
            this.bStorable = bStorable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_SetStorableOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public SqlRecord_SetStorableOut() {
        }
        
        public SqlRecord_SetStorableOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_CopyIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_Copy", Order=0)]
        public int handle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_Copy", Order=1)]
        public int pRecSource;
        
        public SqlRecord_CopyIn() {
        }
        
        public SqlRecord_CopyIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, int pRecSource) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
            this.pRecSource = pRecSource;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_CopyOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public SqlRecord_CopyOut() {
        }
        
        public SqlRecord_CopyOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConnectionIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public GetConnectionIn() {
        }
        
        public GetConnectionIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetConnectionOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.GetConnection", Order=0)]
        public int @return;
        
        public GetConnectionOut() {
        }
        
        public GetConnectionOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenConnectionIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.OpenConnection", Order=0)]
        public string connectionString;
        
        public OpenConnectionIn() {
        }
        
        public OpenConnectionIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string connectionString) {
            this.HeaderInfo = HeaderInfo;
            this.connectionString = connectionString;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class OpenConnectionOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.OpenConnection", Order=0)]
        public int @return;
        
        public OpenConnectionOut() {
        }
        
        public OpenConnectionOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRecordIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.CreateRecord", Order=0)]
        public string tableName;
        
        public CreateRecordIn() {
        }
        
        public CreateRecordIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string tableName) {
            this.HeaderInfo = HeaderInfo;
            this.tableName = tableName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateRecordOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.CreateRecord", Order=0)]
        public int @return;
        
        public CreateRecordOut() {
        }
        
        public CreateRecordOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_CloseIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.Connection_Close", Order=0)]
        public int handle;
        
        public Connection_CloseIn() {
        }
        
        public Connection_CloseIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_CloseOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public Connection_CloseOut() {
        }
        
        public Connection_CloseOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_BeginTransactionIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.Connection_BeginTransaction", Order=0)]
        public int handle;
        
        public Connection_BeginTransactionIn() {
        }
        
        public Connection_BeginTransactionIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_BeginTransactionOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public Connection_BeginTransactionOut() {
        }
        
        public Connection_BeginTransactionOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_CommitIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.Connection_Commit", Order=0)]
        public int handle;
        
        public Connection_CommitIn() {
        }
        
        public Connection_CommitIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_CommitOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public Connection_CommitOut() {
        }
        
        public Connection_CommitOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_RollbackIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.Connection_Rollback", Order=0)]
        public int handle;
        
        public Connection_RollbackIn() {
        }
        
        public Connection_RollbackIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Connection_RollbackOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public Connection_RollbackOut() {
        }
        
        public Connection_RollbackOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtraFilteringIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.GetExtraFiltering", Order=0)]
        public string[] aTablesNames;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.GetExtraFiltering", Order=1)]
        public string aWC;
        
        public GetExtraFilteringIn() {
        }
        
        public GetExtraFilteringIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string[] aTablesNames, string aWC) {
            this.HeaderInfo = HeaderInfo;
            this.aTablesNames = aTablesNames;
            this.aWC = aWC;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExtraFilteringOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.GetExtraFiltering", Order=0)]
        public string @return;
        
        public GetExtraFilteringOut() {
        }
        
        public GetExtraFilteringOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_CloneIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_Clone", Order=0)]
        public int handle;
        
        public SqlRecord_CloneIn() {
        }
        
        public SqlRecord_CloneIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_CloneOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_Clone", Order=0)]
        public int @return;
        
        public SqlRecord_CloneOut() {
        }
        
        public SqlRecord_CloneOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_GetFieldValueIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_GetFieldValue", Order=0)]
        public int handle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_GetFieldValue", Order=1)]
        public string FieldName;
        
        public SqlRecord_GetFieldValueIn() {
        }
        
        public SqlRecord_GetFieldValueIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, string FieldName) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
            this.FieldName = FieldName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_GetFieldValueOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_GetFieldValue", Order=0)]
        public string @return;
        
        public SqlRecord_GetFieldValueOut() {
        }
        
        public SqlRecord_GetFieldValueOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_SetFieldValueIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_SetFieldValue", Order=0)]
        public int handle;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_SetFieldValue", Order=1)]
        public string FieldName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_SetFieldValue", Order=2)]
        public string Value;
        
        public SqlRecord_SetFieldValueIn() {
        }
        
        public SqlRecord_SetFieldValueIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, string FieldName, string Value) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
            this.FieldName = FieldName;
            this.Value = Value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_SetFieldValueOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        public SqlRecord_SetFieldValueOut() {
        }
        
        public SqlRecord_SetFieldValueOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            this.HeaderInfo = HeaderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_IsStorableIn {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_IsStorable", Order=0)]
        public int handle;
        
        public SqlRecord_IsStorableIn() {
        }
        
        public SqlRecord_IsStorableIn(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            this.HeaderInfo = HeaderInfo;
            this.handle = handle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SqlRecord_IsStorableOut {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:Microarea.Web.Services")]
        public Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:Microarea.Web.Services.SqlRecord_IsStorable", Order=0)]
        public bool @return;
        
        public SqlRecord_IsStorableOut() {
        }
        
        public SqlRecord_IsStorableOut(Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, bool @return) {
            this.HeaderInfo = HeaderInfo;
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TbOleDbChannel : Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TbOleDbClient : System.ServiceModel.ClientBase<Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb>, Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb {
        
        public TbOleDbClient() {
        }
        
        public TbOleDbClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TbOleDbClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TbOleDbClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TbOleDbClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_SetStorable(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableIn request) {
            return base.Channel.SqlRecord_SetStorable(request);
        }
        
        public void SqlRecord_SetStorable(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, bool bStorable) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            inValue.bStorable = bStorable;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetStorableOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_SetStorable(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_Copy(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyIn request) {
            return base.Channel.SqlRecord_Copy(request);
        }
        
        public void SqlRecord_Copy(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, int pRecSource) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            inValue.pRecSource = pRecSource;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CopyOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_Copy(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.GetConnection(Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionIn request) {
            return base.Channel.GetConnection(request);
        }
        
        public int GetConnection(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionIn();
            inValue.HeaderInfo = HeaderInfo;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetConnectionOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).GetConnection(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.OpenConnection(Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionIn request) {
            return base.Channel.OpenConnection(request);
        }
        
        public int OpenConnection(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string connectionString) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.connectionString = connectionString;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.OpenConnectionOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).OpenConnection(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.CreateRecord(Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordIn request) {
            return base.Channel.CreateRecord(request);
        }
        
        public int CreateRecord(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string tableName) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.tableName = tableName;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.CreateRecordOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).CreateRecord(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.Connection_Close(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseIn request) {
            return base.Channel.Connection_Close(request);
        }
        
        public void Connection_Close(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CloseOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).Connection_Close(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.Connection_BeginTransaction(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionIn request) {
            return base.Channel.Connection_BeginTransaction(request);
        }
        
        public void Connection_BeginTransaction(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_BeginTransactionOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).Connection_BeginTransaction(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.Connection_Commit(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitIn request) {
            return base.Channel.Connection_Commit(request);
        }
        
        public void Connection_Commit(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_CommitOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).Connection_Commit(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.Connection_Rollback(Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackIn request) {
            return base.Channel.Connection_Rollback(request);
        }
        
        public void Connection_Rollback(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.Connection_RollbackOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).Connection_Rollback(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.GetExtraFiltering(Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringIn request) {
            return base.Channel.GetExtraFiltering(request);
        }
        
        public string GetExtraFiltering(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, string[] aTablesNames, string aWC) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.aTablesNames = aTablesNames;
            inValue.aWC = aWC;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.GetExtraFilteringOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).GetExtraFiltering(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_Clone(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneIn request) {
            return base.Channel.SqlRecord_Clone(request);
        }
        
        public int SqlRecord_Clone(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_CloneOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_Clone(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_GetFieldValue(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueIn request) {
            return base.Channel.SqlRecord_GetFieldValue(request);
        }
        
        public string SqlRecord_GetFieldValue(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, string FieldName) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            inValue.FieldName = FieldName;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_GetFieldValueOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_GetFieldValue(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_SetFieldValue(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueIn request) {
            return base.Channel.SqlRecord_SetFieldValue(request);
        }
        
        public void SqlRecord_SetFieldValue(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle, string FieldName, string Value) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            inValue.FieldName = FieldName;
            inValue.Value = Value;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_SetFieldValueOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_SetFieldValue(inValue);
            HeaderInfo = retVal.HeaderInfo;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableOut Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb.SqlRecord_IsStorable(Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableIn request) {
            return base.Channel.SqlRecord_IsStorable(request);
        }
        
        public bool SqlRecord_IsStorable(ref Microarea.TaskBuilderNet.Core.TbOleDbInterface.TBHeaderInfo HeaderInfo, int handle) {
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableIn inValue = new Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableIn();
            inValue.HeaderInfo = HeaderInfo;
            inValue.handle = handle;
            Microarea.TaskBuilderNet.Core.TbOleDbInterface.SqlRecord_IsStorableOut retVal = ((Microarea.TaskBuilderNet.Core.TbOleDbInterface.TbOleDb)(this)).SqlRecord_IsStorable(inValue);
            HeaderInfo = retVal.HeaderInfo;
            return retVal.@return;
        }
    }
}
