ALTER TABLE "MA_FEPAPARAMETERS"
ADD     "DOCSTATUSCHECKERROR"		 NUMBER(10) DEFAULT(30801920)
GO

UPDATE "MA_FEPAPARAMETERS" SET "DOCSTATUSCHECKERROR" = 30801920 WHERE "DOCSTATUSCHECKERROR" IS NULL
GO

ALTER TABLE "MA_FEPAPARAMETERS"
ADD      "SENDITEMCODE" 			CHAR (1)  DEFAULT('0')
GO

UPDATE "MA_FEPAPARAMETERS" SET "SENDITEMCODE" = '0' WHERE "SENDITEMCODE" IS NULL
GO


ALTER TABLE "MA_FEPAPARAMETERS"
ADD    "ITEMCODETYPE" 			VARCHAR2	(35)  DEFAULT('')
GO

UPDATE "MA_FEPAPARAMETERS" SET "ITEMCODETYPE" = '' WHERE "ITEMCODETYPE" IS NULL
GO
