<?xml version="1.0" encoding="utf-8"?><Database Name="CompanyDevelopmentDMS" Class="DMSModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.DMS_ArchivedDocSearchIndexes" Member="DMS_ArchivedDocSearchIndexes">
    <Type Name="DMS_ArchivedDocSearchIndex">
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SearchIndexID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DMS_SearchFieldIndex_DMS_ArchivedDocSearchIndex" Member="DMS_SearchFieldIndex" ThisKey="SearchIndexID" OtherKey="SearchIndexID" Type="DMS_SearchFieldIndex" IsForeignKey="true" />
      <Association Name="DMS_ArchivedDocument_DMS_ArchivedDocSearchIndex" Member="DMS_ArchivedDocument" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_Attachment" Member="DMS_Attachments">
    <Type Name="DMS_Attachment">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErpDocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CollectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TBCreatedID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBModifiedID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBCreated" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsMainDoc" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AbsoluteCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LotID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsForMail" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Attachment_DMS_AttachmentSearchIndex" Member="DMS_AttachmentSearchIndexes" ThisKey="AttachmentID" OtherKey="AttachmentID" Type="DMS_AttachmentSearchIndex" />
      <Association Name="DMS_Attachment_DMS_SOSDocument" Member="DMS_SOSDocument" ThisKey="AttachmentID" OtherKey="AttachmentID" Type="DMS_SOSDocument" Cardinality="One" />
      <Association Name="DMS_Collection_DMS_Attachment" Member="DMS_Collection" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_Collection" IsForeignKey="true" />
      <Association Name="DMS_ErpDocument_DMS_Attachment" Member="DMS_ErpDocument" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_ErpDocument" IsForeignKey="true" />
      <Association Name="DMS_ArchivedDocument_DMS_Attachment" Member="DMS_ArchivedDocument" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_AttachmentSearchIndexes" Member="DMS_AttachmentSearchIndexes">
    <Type Name="DMS_AttachmentSearchIndex">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SearchIndexID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="DMS_Attachment_DMS_AttachmentSearchIndex" Member="DMS_Attachment" ThisKey="AttachmentID" OtherKey="AttachmentID" Type="DMS_Attachment" IsForeignKey="true" />
      <Association Name="DMS_SearchFieldIndex_DMS_AttachmentSearchIndex" Member="DMS_SearchFieldIndex" ThisKey="SearchIndexID" OtherKey="SearchIndexID" Type="DMS_SearchFieldIndex" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_Collection" Member="DMS_Collections">
    <Type Name="DMS_Collection">
      <Column Name="CollectionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IsStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CollectorID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TemplateName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SosDocClass" Storage="_SosCompatible" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Version" Type="System.Int32" DbType="int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Collection_DMS_Attachment" Member="DMS_Attachments" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_Attachment" />
      <Association Name="DMS_Collection_DMS_CollectionsField" Member="DMS_CollectionsFields" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_CollectionsField" />
      <Association Name="DMS_Collection_DMS_ArchivedDocument" Member="DMS_ArchivedDocuments" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_ArchivedDocument" />
      <Association Name="DMS_Collection_DMS_SOSEnvelope" Member="DMS_SOSEnvelopes" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_SOSEnvelope" />
      <Association Name="DMS_Collector_DMS_Collection" Member="DMS_Collector" ThisKey="CollectorID" OtherKey="CollectorID" Type="DMS_Collector" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_CollectionsFields" Member="DMS_CollectionsFields">
    <Type Name="DMS_CollectionsField">
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(80) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CollectionID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ControlName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OCRPosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PhysicalName" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FieldGroup" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ShowAsDescription" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SosPosition" Type="System.Int32" DbType="int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="HKLName" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SosMandatory" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SosKeyCode" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Collection_DMS_CollectionsField" Member="DMS_Collection" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_Collection" IsForeignKey="true" />
      <Association Name="DMS_Field_DMS_CollectionsField" Member="DMS_Field" ThisKey="FieldName" OtherKey="FieldName" Type="DMS_Field" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_Collector" Member="DMS_Collectors">
    <Type Name="DMS_Collector">
      <Column Name="CollectorID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(128)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsStandard" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Collector_DMS_Collection" Member="DMS_Collections" ThisKey="CollectorID" OtherKey="CollectorID" Type="DMS_Collection" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_ErpDocument" Member="DMS_ErpDocuments">
    <Type Name="DMS_ErpDocument">
      <Column Name="ErpDocumentID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DocNamespace" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PrimaryKeyValue" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DescriptionValue" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBGuid" Type="System.Guid" DbType="uniqueidentifier" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_ErpDocument_DMS_Attachment" Member="DMS_Attachments" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_Attachment" />
      <Association Name="DMS_ErpDocument_DMS_IndexesSynchronization" Member="DMS_IndexesSynchronizations" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_IndexesSynchronization" />
      <Association Name="DMS_ErpDocument_DMS_ErpDocBarcode" Member="DMS_ErpDocBarcodes" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_ErpDocBarcode" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_Field" Member="DMS_Fields">
    <Type Name="DMS_Field">
      <Column Name="FieldName" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FieldDescription" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ValueType" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsCategory" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Field_DMS_CollectionsField" Member="DMS_CollectionsFields" ThisKey="FieldName" OtherKey="FieldName" Type="DMS_CollectionsField" />
      <Association Name="DMS_Field_DMS_FieldProperty" Member="DMS_FieldProperty" ThisKey="FieldName" OtherKey="FieldName" Type="DMS_FieldProperty" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_IndexesSynchronization" Member="DMS_IndexesSynchronizations">
    <Type Name="DMS_IndexesSynchronization">
      <Column Name="SynchID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErpDocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ChangedFields" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DMS_ErpDocument_DMS_IndexesSynchronization" Member="DMS_ErpDocument" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_ErpDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_SearchFieldIndexes" Member="DMS_SearchFieldIndexes">
    <Type Name="DMS_SearchFieldIndex">
      <Column Name="SearchIndexID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FieldValue" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="FormattedValue" Type="System.String" DbType="NVarChar(1024) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DMS_SearchFieldIndex_DMS_ArchivedDocSearchIndex" Member="DMS_ArchivedDocSearchIndexes" ThisKey="SearchIndexID" OtherKey="SearchIndexID" Type="DMS_ArchivedDocSearchIndex" />
      <Association Name="DMS_SearchFieldIndex_DMS_AttachmentSearchIndex" Member="DMS_AttachmentSearchIndexes" ThisKey="SearchIndexID" OtherKey="SearchIndexID" Type="DMS_AttachmentSearchIndex" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_Settings" Member="DMS_Settings">
    <Type Name="DMS_Setting">
      <Column Name="WorkerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SettingType" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Settings" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_ArchivedDocument" Member="DMS_ArchivedDocuments">
    <Type Name="DMS_ArchivedDocument">
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Language" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ExtensionType" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="StorageType" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CreationTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="LastWriteTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="CRC" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Size" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="TBCreatedID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBModifiedID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBCreated" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TBModified" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsWoormReport" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CollectionID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Description" Type="System.String" DbType="NVarchar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Barcode" Type="System.String" DbType="NVarchar(48)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ModifierID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="BarcodeType" Type="System.String" DbType="NVarchar(24)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_ArchivedDocument_DMS_ArchivedDocSearchIndex" Member="DMS_ArchivedDocSearchIndexes" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocSearchIndex" />
      <Association Name="DMS_ArchivedDocument_DMS_Attachment" Member="DMS_Attachments" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_Attachment" />
      <Association Name="DMS_ArchivedDocument_DMS_ArchivedDocContent" Member="DMS_ArchivedDocContent" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocContent" Cardinality="One" />
      <Association Name="DMS_Collection_DMS_ArchivedDocument" Member="DMS_Collection" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_Collection" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_FieldProperties" Member="DMS_FieldProperties">
    <Type Name="DMS_FieldProperty">
      <Column Name="FieldName" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="XMLValues" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FieldColor" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Disabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Field_DMS_FieldProperty" Member="DMS_Field" ThisKey="FieldName" OtherKey="FieldName" Type="DMS_Field" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_TextExtensions" Member="DMS_TextExtensions">
    <Type Name="DMS_TextExtension">
      <Column Name="ExtensionID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExtensionType" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.TB_DBMark" Member="TB_DBMarks">
    <Type Name="TB_DBMark">
      <Column Name="Application" Type="System.String" DbType="NVarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AddOnModule" Type="System.String" DbType="NVarChar(40) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DBRelease" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Status" Type="System.Char" DbType="NChar(1) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ExecLevel3" Type="System.Char" DbType="NChar(1)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="UpgradeLevel" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Step" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_ErpDocBarcodes" Member="DMS_ErpDocBarcodes">
    <Type Name="DMS_ErpDocBarcode">
      <Column Name="Barcode" Type="System.String" DbType="NVarChar(48) NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ErpDocumentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BarcodeType" Type="System.String" DbType="NVarChar(24)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_ErpDocument_DMS_ErpDocBarcode" Member="DMS_ErpDocument" ThisKey="ErpDocumentID" OtherKey="ErpDocumentID" Type="DMS_ErpDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_ArchivedDocContent" Member="DMS_ArchivedDocContents">
    <Type Name="DMS_ArchivedDocContent">
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="BinaryContent" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ExtensionType" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="OCRProcess" Type="System.Boolean" DbType="Bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StorageFile" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_ArchivedDocContent_DMS_ArchivedDocTextContent" Member="DMS_ArchivedDocTextContent" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocTextContent" Cardinality="One" />
      <Association Name="DMS_ArchivedDocument_DMS_ArchivedDocContent" Member="DMS_ArchivedDocument" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocument" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_ArchivedDocTextContent" Member="DMS_ArchivedDocTextContents">
    <Type Name="DMS_ArchivedDocTextContent">
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TextContent" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="DMS_ArchivedDocContent_DMS_ArchivedDocTextContent" Member="DMS_ArchivedDocContent" ThisKey="ArchivedDocID" OtherKey="ArchivedDocID" Type="DMS_ArchivedDocContent" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_DocumentToArchive" Member="DMS_DocumentToArchives">
    <Type Name="DMS_DocumentToArchive">
      <Column Name="DocToArchivedID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="ExtensionType" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="CreationTimeUtc" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DocContent" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_SOSConfiguration" Member="DMS_SOSConfigurations">
    <Type Name="DMS_SOSConfiguration">
      <Column Name="SubjectCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="AncestorCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="KeeperCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MySOSUser" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="MySOSPassword" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DocClasses" Type="System.Xml.Linq.XElement" DbType="Xml  NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SOSWebServiceUrl" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ParamID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="ChunkDimension" Type="System.Int32" DbType="Int NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EnvelopeDimension" Type="System.Int32" DbType="Int NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FTPSend" Type="System.Boolean" DbType="bit" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FTPSharedFolder" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FTPUpdateDayOfWeek" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_SOSDocument" Member="DMS_SOSDocuments">
    <Type Name="DMS_SOSDocument">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DescriptionKeys" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="HashCode" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DocumentStatus" Type="System.Int32" DbType="int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="AbsoluteCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LotID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArchivedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="RegistrationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="EnvelopeID" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(256) NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Size" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TaxJournal" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DocumentType" Type="System.String" DbType="NVarChar(25)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="FiscalYear" Type="System.String" DbType="NVarChar(4)" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="SendingType" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_Attachment_DMS_SOSDocument" Member="DMS_Attachment" ThisKey="AttachmentID" OtherKey="AttachmentID" Type="DMS_Attachment" IsForeignKey="true" />
      <Association Name="DMS_SOSEnvelope_DMS_SOSDocument" Member="DMS_SOSEnvelope" ThisKey="EnvelopeID" OtherKey="EnvelopeID" Type="DMS_SOSEnvelope" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_SOSEnvelope" Member="DMS_SOSEnvelopes">
    <Type Name="DMS_SOSEnvelope">
      <Column Name="EnvelopeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DispatchDate" Storage="_DispatchTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CollectionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="DispatchStatus" Type="System.Int32" DbType="int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DispatchCode" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SynchronizedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="LoginId" Type="System.Int32" DbType="Int" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="SendingType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreationDate" AutoSync="Never" Type="System.DateTime" DbType="DateTime" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="DMS_SOSEnvelope_DMS_SOSDocument" Member="DMS_SOSDocuments" ThisKey="EnvelopeID" OtherKey="EnvelopeID" Type="DMS_SOSDocument" />
      <Association Name="DMS_Collection_DMS_SOSEnvelope" Member="DMS_Collection" ThisKey="CollectionID" OtherKey="CollectionID" Type="DMS_Collection" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DMS_WFAttachments" Member="DMS_WFAttachments">
    <Type Name="DMS_WFAttachments">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ApprovalStatus" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkerID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RequestDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ApproverID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ApprovalDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RequestComments" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="ApprovalComments" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.udf_FTS_SearchAttachments" Method="udf_FTS_SearchAttachments" IsComposable="true">
    <Parameter Name="CollectorID" Parameter="collectorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="CollectionID" Parameter="collectionID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ErpDocumentID" Parameter="erpDocumentID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ExtensionType" Parameter="extensionType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DataFrom" Parameter="dataFrom" Type="System.DateTime" DbType="Date" />
    <Parameter Name="DataTo" Parameter="dataTo" Type="System.DateTime" DbType="Date" />
    <Parameter Name="keywords" Type="System.String" DbType="NVarChar(4000)" />
    <ElementType Name="udf_FTS_SearchAttachmentsResult">
      <Column Name="AttachmentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.udf_FTS_SearchArchivedDoc" Method="udf_FTS_SearchArchivedDoc" IsComposable="true">
    <Parameter Name="ExtensionType" Parameter="extensionType" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="DataFrom" Parameter="dataFrom" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DataTo" Parameter="dataTo" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OnlyWoormReport" Parameter="onlyWoormReport" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OnlyNotAttached" Parameter="onlyNotAttached" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OnlyAttached" Parameter="onlyAttached" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="OnlyPending" Parameter="onlyPending" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="keywords" Type="System.String" DbType="NVarChar(4000)" />
    <ElementType Name="udf_FTS_SearchArchivedDocResult">
      <Column Name="ArchivedDocID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.udf_GetUnusedFieldIndexes" Method="udf_GetUnusedFieldIndexes" IsComposable="true">
    <ElementType Name="udf_GetUnusedFieldIndexesResult">
      <Column Name="SearchIndexID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>