
#pragma once

//============================================================================
#define	ID_BEGIN_SORT		13001
#define	ID_END_SORT			13002
#define	ID_SORT_TIC			13003

#define	ID_BEGIN_GROUP		13004
#define	ID_END_GROUP		13005
#define	ID_GROUP_TIC		13006

#define	ID_BEGIN_MEM_GROUP	13007
#define	ID_END_MEM_GROUP	13008
#define	ID_MEM_GROUP_TIC	13009

#define ID_SEARCH_TIC       13010
#define	ID_RETRIEVE_TIC		13011


