CREATE TABLE "MA_FEPAPARAMETERS" ( 
    "PARAMETERID"			 INTEGER NOT NULL,
    "SERVERNAME"			 VARCHAR2	(32)	DEFAULT(''),
    "DBNAME"				 VARCHAR2	(32)	DEFAULT(''),
    "USERNAME"				 VARCHAR2	(32)	DEFAULT(''),
    "PASSWORD"				 VARCHAR2	(32)	DEFAULT(''),
    "COMPANYCODE"			 VARCHAR2	(8)		DEFAULT(''),
	"DOCSTATUSCHECKERROR"	 NUMBER		(10)	DEFAULT(10682368),
	"USEINTERNALTRANSCODING" CHAR		(1)		DEFAULT('0'),
	"PROCESSCODEB2B"         VARCHAR2   (2)		DEFAULT(''),
   CONSTRAINT "PK_FEPAPARAMETERS" PRIMARY KEY
    (
        "PARAMETERID"
    )
)
GO



