CREATE TABLE "MA_EIPARAMETERS" ( 
    "PARAMETERID" INTEGER NOT NULL,
	"ATTACHREPORT"		   CHAR		 (1) DEFAULT ('0'),
   "DOCUMENTPATH"         VARCHAR2(128) DEFAULT(''),
   CONSTRAINT "PK_EIPARAMETERS" PRIMARY KEY
    (
        "PARAMETERID"
    )
)
GO



