CREATE TABLE "MA_EICODING" (
    "EITYPE" NUMBER (10) DEFAULT (31916032) NOT NULL ,
    "EICODE" VARCHAR2 (8) NOT NULL,
    "DESCRIPTION" VARCHAR2 (128) DEFAULT (''),
    "DISABLED" CHAR (1) DEFAULT ('0'),
    CONSTRAINT "PK_EICODING" PRIMARY KEY
    (
        "EITYPE",
        "EICODE"
    )
)
GO
