CREATE TABLE "AUDIT_NAMESPACES" (
	"ID" NUMBER(10) NOT NULL,
    "NAMESPACE" /*[SKIPUNICODE]*/ VARCHAR2(256) NOT NULL, 
    "TYPENS" NUMBER(6) DEFAULT(0) NOT NULL,
    CONSTRAINT "PK_AUDIT_NAMESPACES" PRIMARY KEY("ID") 
    USING INDEX )
GO

CREATE TABLE "AUDIT_TABLES" (
	"TABLENAME" /*[SKIPUNICODE]*/ VARCHAR2(128) NOT NULL, 
	"STARTTRACE" DATE, 
	"SUSPENDED" CHAR(1) DEFAULT('0'), 
    CONSTRAINT "PK_AUDIT_TABLES" PRIMARY KEY("TABLENAME") 
    USING INDEX )
GO