ALTER TABLE "MA_FEPAPARAMETERS"
ADD "PROCESSCODEPA" VARCHAR2(2)	DEFAULT('')
GO


UPDATE "MA_FEPAPARAMETERS" SET "PROCESSCODEPA" = '' WHERE "PROCESSCODEPA" IS NULL
GO

ALTER TABLE "MA_FEPAPARAMETERS"
ADD "PROCESSCODEB2B" VARCHAR2(2) DEFAULT('')
GO


UPDATE "MA_FEPAPARAMETERS" SET "PROCESSCODEB2B" = '' WHERE "PROCESSCODEB2B" IS NULL
GO

