CREATE TABLE "XE_PARAMETERS" (
    "IDPARAM" NUMBER(6) NOT NULL,
    "DOMAINNAME" /*[SKIPUNICODE]*/ VARCHAR2(64) DEFAULT(''), 
    "SITENAME" /*[SKIPUNICODE]*/ VARCHAR2(64) DEFAULT(''),
    "SITECODE" /*[SKIPUNICODE]*/ VARCHAR2(4) DEFAULT(''), 
    "ENCODINGTYPE" VARCHAR2(1) DEFAULT('1'), 
    "IMPORTPATH" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    "EXPORTPATH" /*[SKIPUNICODE]*/ VARCHAR2(256) DEFAULT(''), 
    "MAXDOC" NUMBER(6) DEFAULT(10), 
    "MAXKBYTE" NUMBER(6) DEFAULT(100), 
    "USEENVCLASSEXT" CHAR(1) DEFAULT('0'), 
    "ENVPADDINGNUM" NUMBER(6) DEFAULT(4), 
    "USEATTRIBUTE" CHAR(1) DEFAULT('0'), 
    "USEENUMASNUM" CHAR(1) DEFAULT('1'),   
    CONSTRAINT "PK_XE_PARAMETERS" PRIMARY KEY("IDPARAM") 
    USING INDEX  )
GO

DECLARE
   XE_SITEPARAMSCOUNT INT;
   XE_PARAMETERSCOUNT INT;

BEGIN
  SELECT COUNT(*) INTO XE_SITEPARAMSCOUNT FROM "XE_SITEPARAMS";
  SELECT COUNT(*) INTO XE_PARAMETERSCOUNT FROM "XE_PARAMETERS";

  IF XE_PARAMETERSCOUNT = 0 THEN
	BEGIN
		IF XE_SITEPARAMSCOUNT > 0 THEN
			INSERT INTO "XE_PARAMETERS" ("IDPARAM", "DOMAINNAME", "SITENAME", "SITECODE", "ENCODINGTYPE", "IMPORTPATH", "EXPORTPATH")
			SELECT "XE_SITEPARAMS"."IDPARAM", "XE_SITEPARAMS"."DOMAINNAME" , "XE_SITEPARAMS"."SITENAME", "XE_SITEPARAMS"."SITECODE", 
			"XE_SITEPARAMS"."ENCODINGTYPE", "XE_SITEPARAMS"."IMPORTPATH", "XE_SITEPARAMS"."EXPORTPATH"
			FROM "XE_SITEPARAMS"
			WHERE "XE_SITEPARAMS"."IDPARAM" = 1;
		ELSE
			INSERT INTO "XE_PARAMETERS"("IDPARAM", "DOMAINNAME", "SITENAME", "SITECODE") VALUES (1, 'DEFAULT_DOMAIN', 'DEFAULT_SITE', 'DESI');
		END IF;
	  END;
  END IF;
END;
GO

DECLARE NUMB INT;   

BEGIN
  SELECT COUNT(*) INTO NUMB FROM "XE_TRANSFERPARAMS";
  IF NUMB > 0 THEN
	UPDATE "XE_PARAMETERS"  
	SET ("MAXDOC", "MAXKBYTE", "USEENVCLASSEXT", "ENVPADDINGNUM", "USEATTRIBUTE", "USEENUMASNUM") = 
	(SELECT "XE_TRANSFERPARAMS"."MAXDOC", "XE_TRANSFERPARAMS"."MAXKBYTE", "XE_TRANSFERPARAMS"."USEENVCLASSEXT", 
	"XE_TRANSFERPARAMS"."ENVPADDINGNUM", "XE_TRANSFERPARAMS"."USEATTRIBUTE", "XE_TRANSFERPARAMS"."USEENUMASNUM" 
	FROM "XE_TRANSFERPARAMS" 
	INNER JOIN "XE_PARAMETERS" ON "XE_PARAMETERS"."IDPARAM" = "XE_TRANSFERPARAMS"."IDPARAM"); 
  END IF;
END;
GO

DROP TABLE "XE_SITEPARAMS"
GO

DROP TABLE "XE_TRANSFERPARAMS"
GO
