// -----------------------------------------------------------------------
// <copyright file="BaseDeclarator.cs" company="Microarea S.p.A.">
// TODO: Update copyright text.
// </copyright>
// -----------------------------------------------------------------------

namespace Microarea.TaskBuilderNet.Core.EasyBuilder
{
	using System;
	using System.CodeDom;

	//=========================================================================
	/// <summary>
	/// BaseDeclarator
	/// </summary>
	public class BaseDeclarator
	{
		//---------------------------------------------------------------------
		protected BaseDeclarator()
		{

		}

		//---------------------------------------------------------------------
		protected void AddHeaderComment(CodeNamespace codeNamespace)
		{
			CodeCommentStatement comment = new CodeCommentStatement("---------------------------------------------------------------------");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement(" <auto-generated>");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("     This code was generated by an automatic tool.");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement(String.Format("     Runtime Version:{0}", Environment.Version.ToString()));
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("     Changes to this file will be lost if the code is regenerated.");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("     Use 'partial' keyword in a new file to modify this classes.");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement(" </auto-generated>");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("---------------------------------------------------------------------");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("");
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement(String.Format(" This source code was auto-generated by {0} from {1}.", this.GetType().FullName, this.GetType().Assembly.GetName().FullName));
			codeNamespace.Comments.Add(comment);
			comment = new CodeCommentStatement("");
			codeNamespace.Comments.Add(comment);
		}

		//---------------------------------------------------------------------
		public static string GetFieldName(string columnName)
		{
			return String.Concat("_f_", columnName);
		}

		//---------------------------------------------------------------------
		public static string GetLocalFieldName(string localFieldPropertyName)
		{
			return String.Concat("_", localFieldPropertyName);
		}
	}
}
