INSERT INTO MA_EI_ITCUSTSUPPADDDATA (CUSTSUPP, CUSTSUPPTYPE) VALUES ('*', 3211264)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiOrdineAcquisto.IdDocumento', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiOrdineAcquisto.Data', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiOrdineAcquisto.CodiceCommessaConvenzione', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiOrdineAcquisto.CodiceCUP', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiOrdineAcquisto.CodiceCIG', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiFattureCollegate.IdDocumento', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiFattureCollegate.Data', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiFattureCollegate.CodiceCommessaConvenzione', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiFattureCollegate.CodiceCUP', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiFattureCollegate.CodiceCIG', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiDDT.NumeroDDT', 11599873)
GO

INSERT INTO MA_EI_ITCUSTSUPPADDDATADET (CUSTSUPP, CUSTSUPPTYPE, FIELDNAME, FIELDMESSAGE) VALUES ('*', 3211264, 'FatturaElettronica.FatturaElettronicaBody.DatiGenerali.DatiDDT.DataDDT', 11599873)
GO
