ALTER TABLE "TB_DBMARK" DROP COLUMN "RELEASE"
GO

ALTER TABLE "TB_DBMARK" ADD "RELEASEDATE" DATE DEFAULT(sysdate)
GO

UPDATE "TB_DBMARK" SET "RELEASEDATE" = "DATARELEASE" WHERE "TB_DBMARK"."RELEASEDATE" IS NULL
GO

ALTER TABLE "TB_DBMARK" DROP COLUMN "DATARELEASE"
GO
